### ISSUE TITLE
please quick！

### ISSUE THREAD

**Issue by robotzheng** [google-research/bert#1]
I am very curious about it. how on squad 2.0?

**Comment by loretoparisi** [comment]
💯 👍

**Comment by jacobdevlin-google** [comment]
We haven't run on SQuAD 2.0 since we figured that as soon as the source was released (with push-button replication on SQuAD v1.1) lots of people would do it. So please try and report back!

**Comment by johndpope** [comment]
<img width="790" alt="screen shot 2018-10-31 at 11 51 49 am" src="https://user-images.githubusercontent.com/289994/47800865-68f00180-dd03-11e8-8dff-b78e3ad06c21.png">
