### ISSUE TITLE
Possible to release the final dense layer in pre training

### ISSUE THREAD

**Issue by llsguoqing** [google-research/bert#102]
Hi,

Just wondering is it possible to get the last dense layer created during the pre-training phase (variables defined in https://github.com/google-research/bert/blob/master/run_pretraining.py#L245). We are trying to evaluate whether this can be used as a better version of context2vec, which provides viable alternatives for each word in the sentence.

**Comment by thomwolf** [comment]
Hi I saw them in the checkpoint files. If you list the variables there, you will find them at the end.

**Comment by jacobdevlin-google** [comment]
Yes they should be there for all of the released models, let me know if they are missing for any of them.
