### ISSUE TITLE
how to run bert with multi GPU on demo 

### ISSUE THREAD

**Issue by Matrixsun** [google-research/bert#104]
hi everyone, I am new one with tensorflow . how change the bert code for multi GPU on a server

**Comment by jacobdevlin-google** [comment]
We don't plan on supporting Multi-GPU, you'll have to look for someone's fork or use the generic [distributed TensorFlow](https://www.tensorflow.org/deploy/distributed) mechanism.

**Comment by MrRace** [comment]
so BERT does not support Multi-GPU when training?
