### ISSUE TITLE
BERT-Tiny,BERT-Mini,BERT-Small,BERT-Medium - TF 2.0 checkpoints 

### ISSUE THREAD

**Issue by 17patelumang** [google-research/bert#1066]
Hi All , 

I am looking at BERT checkpoint here - https://github.com/tensorflow/models/tree/master/official/nlp/bert for TF 2.0 .

Are checkpoints for BERT-Tiny,BERT-Mini,BERT-Small,BERT-Medium avaialbe in TF 2.0 ?

**Comment by dpManuqb** [comment]
Check automodel from transformers library of huggingface.  https://huggingface.co/transformers/

**Comment by maziyarpanahi** [comment]
There are small BERT models here, maybe they can be used in TF 2.x: https://tfhub.dev/google/collections/bert/1
