### ISSUE TITLE
module 'tensorflow_core._api.v2.train' has no attribute 'Saver'

### ISSUE THREAD

**Issue by adarshrana205** [google-research/bert#1087]
train(model, x_train, y_train, x_test, y_test)
 export_model(tf.train.Saver(), model, ["conv2d_1_input"], "dense_2/Softmax")
     
AttributeError: module 'tensorflow_core._api.v2.train' has no attribute 'Saver'

**Comment by Tarun3679** [comment]
Hi,if you are using tensorflow 2.x, then you can try to replace tf.train.Saver() by tf.compat.v1.train.Saver()

**Comment by adarshrana205** [comment]
I used that also(tf.compat.v1.train.Saver()) but another error is occuring which is like

if var_list is None:
             raise RuntimeError(
          "When eager execution is enabled, `var_list` must specify a list "
           "or dict of variables to save")
         self._var_list = var_list


RuntimeError: When eager execution is enabled, `var_list` must specify a list or dict of variables to save
 

Please tell me regarding it...

**Comment by Tarun3679** [comment]
Well according to 2.2 documentation you will have to specify what varlist is in the parameters of the function.
https://www.tensorflow.org/api_docs/python/tf/compat/v1/train/Saver

**Comment by Haseebullah010** [comment]
Hi, this error resolved by using tf.compat.v1.train.Saver(). And the version of my tensor flow is 2.2.0.

**Comment by nabilahnran** [comment]
> Well according to 2.2 documentation you will have to specify what varlist is in the parameters of the function. https://www.tensorflow.org/api_docs/python/tf/compat/v1/train/Saver

in this author case, what should i fill in varlist? sorry im confused @Tarun3679 @adarshrana205
