### ISSUE TITLE
How to redirect logging to a file?

### ISSUE THREAD

**Issue by FynnYoung** [google-research/bert#109]
I want to redirect tensorflow logging to a file, where tensorflow logging means the information that is outputted to screen:
INFO:tensorflow:examples/sec: ......
INFO:tensorflow:global_step/sec: ......

I have tried command like:
python run_classifier.py ...... > log.txt
but it does work. Does anyone know how to do that?

**Comment by ghostplant** [comment]
@jacobdevlin-google How to enable this benchmark logging message when `--do_predict=True`?

**Comment by zjplab** [comment]
My way:
`cmd 2>&1 | tee output.txt`
