### ISSUE TITLE
I don't know how to properly use fine tuned Bert Model

### ISSUE THREAD

**Issue by XINZHANG-ops** [google-research/bert#1097]
1. So what I need to do is train a fine turned model on multi-classes classification and use it locally.

2. I followed the tutorial from this link:
https://colab.research.google.com/github/tensorflow/tpu/blob/master/tools/colab/bert_finetuning_with_cloud_tpus.ipynb

3. I created a bucket to save its outputs, and I load my own data from my drive. After training, I have these files in the bucket.
<img width="308" alt="Screen Shot 2020-06-03 at 9 12 01 PM" src="https://user-images.githubusercontent.com/47906299/83704020-fb8f0b80-a5de-11ea-910b-51d337bdd75b.png">

4. It works all perfectly fine on the colab.

5. But I want to use the trained model locally. So I read this article:
https://towardsdatascience.com/3-ways-to-optimize-and-export-bert-model-for-online-serving-8f49d774a501

6. So I download the all stuff generated into the bucket, includes model.ckpt-14226
<img width="892" alt="Screen Shot 2020-06-03 at 9 25 00 PM" src="https://user-images.githubusercontent.com/47906299/83704700-dd2a0f80-a5e0-11ea-8242-ce48c002c01a.png">

7. And I follow the steps from the article, when I run this block of codes (These codes are in the article from the above link)

<img width="715" alt="Screen Shot 2020-06-03 at 9 19 35 PM" src="https://user-images.githubusercontent.com/47906299/83704413-072f0200-a5e0-11ea-833e-e93e7aa68376.png">

7.  I run into these errors. So anyone can help me with this, thank you!

INFO:tensorflow:Restoring parameters from ./EvalOutput/model.ckpt-14226
---------------------------------------------------------------------------
InvalidArgumentError                      Traceback (most recent call last)
/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tensorflow_core/python/client/session.py in _do_call(self, fn, *args)
   1364     try:
-> 1365       return fn(*args)
   1366     except errors.OpError as e:

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tensorflow_core/python/client/session.py in _run_fn(feed_dict, fetch_list, target_list, options, run_metadata)
   1347       # Ensure any changes to the graph are reflected in the runtime.
-> 1348       self._extend_graph()
   1349       return self._call_tf_sessionrun(options, feed_dict, fetch_list,

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tensorflow_core/python/client/session.py in _extend_graph(self)
   1387     with self._graph._session_run_lock():  # pylint: disable=protected-access
-> 1388       tf_session.ExtendSession(self._session)
   1389 

InvalidArgumentError: No OpKernel was registered to support Op 'TPUReplicateMetadata' used by {{node TPUReplicateMetadata}}with these attrs: [allow_soft_placement=false, num_cores_per_replica=1, use_tpu=true, num_replicas=8, computation_shape=[], host_compute_core=[], device_assignment=[], padding_map=[], _tpu_replicate="cluster", step_marker_location="STEP_MARK_AT_TOP_LEVEL_WHILE_LOOP", topology=""]
Registered devices: [CPU, XLA_CPU]
Registered kernels:
  <no registered kernels>

	 [[TPUReplicateMetadata]]

During handling of the above exception, another exception occurred:

InvalidArgumentError                      Traceback (most recent call last)
/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tensorflow_core/python/training/saver.py in restore(self, sess, save_path)
   1289         sess.run(self.saver_def.restore_op_name,
-> 1290                  {self.saver_def.filename_tensor_name: save_path})
   1291     except errors.NotFoundError as err:

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tensorflow_core/python/client/session.py in run(self, fetches, feed_dict, options, run_metadata)
    955       result = self._run(None, fetches, feed_dict, options_ptr,
--> 956                          run_metadata_ptr)
    957       if run_metadata:

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tensorflow_core/python/client/session.py in _run(self, handle, fetches, feed_dict, options, run_metadata)
   1179       results = self._do_run(handle, final_targets, final_fetches,
-> 1180                              feed_dict_tensor, options, run_metadata)
   1181     else:

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tensorflow_core/python/client/session.py in _do_run(self, handle, target_list, fetch_list, feed_dict, options, run_metadata)
   1358       return self._do_call(_run_fn, feeds, fetches, targets, options,
-> 1359                            run_metadata)
   1360     else:

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tensorflow_core/python/client/session.py in _do_call(self, fn, *args)
   1383                     'disable_meta_optimizer = True')
-> 1384       raise type(e)(node_def, op, message)
   1385 

InvalidArgumentError: No OpKernel was registered to support Op 'TPUReplicateMetadata' used by node TPUReplicateMetadata (defined at /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py:1748) with these attrs: [allow_soft_placement=false, num_cores_per_replica=1, use_tpu=true, num_replicas=8, computation_shape=[], host_compute_core=[], device_assignment=[], padding_map=[], _tpu_replicate="cluster", step_marker_location="STEP_MARK_AT_TOP_LEVEL_WHILE_LOOP", topology=""]
Registered devices: [CPU, XLA_CPU]
Registered kernels:
  <no registered kernels>

	 [[TPUReplicateMetadata]]

During handling of the above exception, another exception occurred:

InvalidArgumentError                      Traceback (most recent call last)
<ipython-input-2-1189dd9d05b9> in <module>
     10 sess = tf.Session()
     11 imported_meta = tf.train.import_meta_graph(os.path.join(path, 'model.ckpt-14226.meta')) #based on the steps of your fine-tuned model
---> 12 imported_meta.restore(sess, os.path.join(path, 'model.ckpt-14226')) #based on the steps of your fine-tuned model
     13 my_vars = []
     14 for var in tf.all_variables():

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tensorflow_core/python/training/saver.py in restore(self, sess, save_path)
   1324       # We add a more reasonable error message here to help users (b/110263146)
   1325       raise _wrap_restore_error_with_msg(
-> 1326           err, "a mismatch between the current graph and the graph")
   1327 
   1328   @staticmethod

InvalidArgumentError: Restoring from checkpoint failed. This is most likely due to a mismatch between the current graph and the graph from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint. Original error:

No OpKernel was registered to support Op 'TPUReplicateMetadata' used by node TPUReplicateMetadata (defined at /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py:1748) with these attrs: [allow_soft_placement=false, num_cores_per_replica=1, use_tpu=true, num_replicas=8, computation_shape=[], host_compute_core=[], device_assignment=[], padding_map=[], _tpu_replicate="cluster", step_marker_location="STEP_MARK_AT_TOP_LEVEL_WHILE_LOOP", topology=""]
Registered devices: [CPU, XLA_CPU]
Registered kernels:
  <no registered kernels>

	 [[TPUReplicateMetadata]]

**Comment by jageshmaharjan** [comment]
Take a look at this, maybe this could be the one that you are looking for,
[BERT inference](https://medium.com/delvify/bert-rest-inference-from-the-fine-tuned-model-499997b32851)
