### ISSUE TITLE
Missing requirements.txt

### ISSUE THREAD

**Issue by winston-zillow** [google-research/bert#11]
Hope to see this file added so we can tell what versions of tensorlfow and other libraries are supported.

**Comment by jacobdevlin-google** [comment]
I'll add this file.

It's just tensorflow, tested on 1.11.0, but it may work back to 1.7.0.

**Comment by winston-zillow** [comment]
It would try to import `tf.contrib.tpu.InputPipelineConfig.PER_HOST_V2` even if one doesn't use TPU and this symbol is available in TF 1.9 or above.

**Comment by jacobdevlin-google** [comment]
Ok I added requirements.txt with 1.11.0 then, thanks.
