### ISSUE TITLE
Restore model each time doing  estimator.predict

### ISSUE THREAD

**Issue by mfxss** [google-research/bert#114]
I am using the code from `extract_features.py` . I called `model_fn_builder` only once. And create several `examples` list to feed to `estimator.predict` . It seems that each time doing `estimator.predict`, the model is restored which can be seen from the logger info.  This slows down. Where can I fix this?

**Comment by jacobdevlin-google** [comment]
I think that's the expected behavior of this interface, so if you need different behavior you can change the interface to something other than TPUEstimator.

**Comment by hanxiao** [comment]
@mfxss I solved this problem in this repo, and wrap the extract_features as a service. please refer to it: https://github.com/hanxiao/bert-as-service
the avg. speed for 12 layer BERT with `max_seq_len` is about 2000 sample/s

**Comment by ntson2002** [comment]
> @mfxss I solved this problem in this repo, and wrap the extract_features as a service. please refer to it: https://github.com/hanxiao/bert-as-service
> the avg. speed for 12 layer BERT with `max_seq_len` is about 2000 sample/s



> @mfxss I solved this problem in this repo, and wrap the extract_features as a service. please refer to it: https://github.com/hanxiao/bert-as-service
> the avg. speed for 12 layer BERT with `max_seq_len` is about 2000 sample/s



> @mfxss I solved this problem in this repo, and wrap the extract_features as a service. please refer to it: https://github.com/hanxiao/bert-as-service
> the avg. speed for 12 layer BERT with `max_seq_len` is about 2000 sample/s

Could you point out the behind idea and the code ? Thank you very much.

**Comment by hanxiao** [comment]
@ntson2002 checkout https://hanxiao.github.io/2019/01/02/Serving-Google-BERT-in-Production-using-Tensorflow-and-ZeroMQ/

**Comment by guotong1988** [comment]
Mark
