### ISSUE TITLE
AttributeError: module 'tensorflow._api.v2.train' has no attribute 'Optimizer'

### ISSUE THREAD

**Issue by devmaster815** [google-research/bert#1140]
Hello! I runed this source code but I have an issue.
Traceback (most recent call last):
  File "f:\studying\Artificial Intelligence\tensorflow\overimagination\bert\bert-master\run_classifier.py", line 25, in <module>
    import optimization
  File "f:\studying\Artificial Intelligence\tensorflow\overimagination\bert\bert-master\optimization.py", line 87, in <module>
    class AdamWeightDecayOptimizer(tf.train.Optimizer):
AttributeError: module 'tensorflow._api.v2.train' has no attribute 'Optimizer'

**Comment by miutamihai** [comment]
Same here. Using `Ubuntu 20.04`, `Python 3.8.2` and `Tensorflow-GPU 2.3.0`.

**Comment by javedulferdous** [comment]
I'm having this error as well.
Does anyone has an idea to resolve this issue?
Thanks

**Comment by miutamihai** [comment]
I finally figured it out. It seems that the `Optimizer` class has been deprecated in the `2.x` versions of Tensorflow. As [this](https://github.com/tensorflow/tensorflow/issues/39768) issue can attest, you will need to install an older version of `Python` too (I used `3.7`). You can then run `python3.7 -m pip install tensorflow==1.15.0` and you should have the correct version installed. That fixed it for me.

**Comment by dilanSachi** [comment]
@miutamihai worked for me too

**Comment by abhilash1910** [comment]
Hi, raised a PR #1155  to resolve this issue for tf versions greater than 2.0.
Thanks

**Comment by Krishnarohith10** [comment]
It has been moved to tf.compat.v1 `Optimizers` class. Check it and please try to close the issue.

**Comment by Krishnarohith10** [comment]
> I finally figured it out. It seems that the `Optimizer` class has been deprecated in the `2.x` versions of Tensorflow. As [this](https://github.com/tensorflow/tensorflow/issues/39768) issue can attest, you will need to install an older version of `Python` too (I used `3.7`). You can then run `python3.7 -m pip install tensorflow-gpu==1.15.0` (or just `tensorflow==1.15.0` for the CPU version) and you should have the correct version installed. That fixed it for me.

Since you figured this, we also use previous 1.X version from current 2.X version. `tf.compat.v1` contains all the 1.X version packages. So just try `tf.compat.v1.MomentumOptimizer`.

**Comment by devmaster815** [comment]
Closing this issue since it was solved.

**Comment by vesper1012** [comment]
bert-base-ner-train -help
ImportError: cannot import name 'trace'
my python 3.6 tensorflow 1.15.0

**Comment by mayongfei929** [comment]
Optimizer在tensorflow2.x的版本中已经被弃用了，所以针对模块 'tensorflow._api.v2.train' 没有属性 'Optimizer'问题，可以采用重装tensorflow1.x的版本解决（tensorflow-gpu同理）
