### ISSUE TITLE
how to save the best model according to the valid dataset

### ISSUE THREAD

**Issue by liu-nlper** [google-research/bert#115]

**Comment by jacobdevlin-google** [comment]
You can look into the Estimator API, but I would recommend just saving a lot of checkpoints by setting `keep_checkpoint_max` to a large value in `tf.contrib.tpu.RunConfig` and then evaluating after the fact by passing checkpoints from various epochs as `init_checkpoint`.

**Comment by Nidhi-kumari** [comment]
Do we still have to do using keep_checkpoint_max or do we have another fix for this . we have to do evaluation for each checkpoint. what if we have so many checkpoint model
