### ISSUE TITLE
No ckpt.meta file in the release of 24 smaller BERT models

### ISSUE THREAD

**Issue by qfdong** [google-research/bert#1172]
I can only find:
1. bert_config.json
2. bert_model.ckpt.data-00000-of-00001
3. bert_model.ckpt.index
4. vocab.txt

seems bert_model.ckpt.meta is missing

**Comment by geo47** [comment]
It seems strange, anyways you can download from [this link](https://storage.googleapis.com/bert_models/2018_10_18/cased_L-12_H-768_A-12.zip):

**Comment by qfdong** [comment]
> It seems strange, anyways you can download from [this link](https://storage.googleapis.com/bert_models/2018_10_18/cased_L-12_H-768_A-12.zip):

Thanks a lot. I downloaded that from the link you provided and everything I needed is there.

**Comment by ValleZ** [comment]
Why there are no meta files?

**Comment by sauravpr** [comment]
> > It seems strange, anyways you can download from [this link](https://storage.googleapis.com/bert_models/2018_10_18/cased_L-12_H-768_A-12.zip):
> 
> Thanks a lot. I downloaded that from the link you provided and everything I needed is there.

The link only works for the 12 layer BERT-base model, what about the other models?
