### ISSUE TITLE
Cloud bucket error when pretraining on colab

### ISSUE THREAD

**Issue by chiayewken** [google-research/bert#126]
Thank you for your research work. Adapting the run_pretraining code to the run_classifier notebook code, and followed the same setup. The run_classifier code is able to train successfully on colab. However, the run_pretraining code results in the following error and it only works when I train on GPU instead. 

Unsuccessful TensorSliceReader constructor: Failed to get matching files on gs://ken_bucket/bert/models/plays/model.ckpt-0: Permission denied: Error executing an HTTP request: HTTP response code 403 with body '{
 "error": {
  "errors": [
   {
    "domain": "global",
    "reason": "forbidden",
    "message": "service-495559152420@cloud-tpu.iam.gserviceaccount.com does not have storage.objects.list access to ken_bucket."
   }
  ],
  "code": 403,
  "message": "service-495559152420@cloud-tpu.iam.gserviceaccount.com does not have storage.objects.list access to ken_bucket."
 }
}

**Comment by chiayewken** [comment]
Solved, Turns out the tfrecord data also needs to be in the cloud bucket, not locally.

**Comment by damnko** [comment]
Hey @chiayewken I'm having the same problem. Would you mind elaborating more on your solution?
I've uploaded the train/dev dataset to the bucket and the git repo content in the tpu. What do you mean by "the tfrecord data also needs to be in the cloud bucket" ?
Thanks

**Comment by rusiaaman** [comment]
Faced the same issue as @damnko ended making my own bucket on gcloud an copying the bert model over there instead of gs://bert_models/2018_10_18/uncased_L-12_H-768_A-12

**Comment by pratibha5** [comment]
I am unable to access my own storage in spite of copying the models on to my bucket. Still getting the same exception

InvalidArgumentError (see above for traceback): Unsuccessful TensorSliceReader constructor: Failed to get matching files on gs://bert_model_uncased_12/bert_model.ckpt: Permission denied: Error executing an HTTP request: HTTP response code 403 with body '{
 "error": {
  "errors": [
   {
    "domain": "global",
    "reason": "forbidden",
    "message": "service-495559152420@cloud-tpu.iam.gserviceaccount.com does not have storage.objects.list access to bert_model_uncased_12."
   }
  ],
  "code": 403,
  "message": "service-495559152420@cloud-tpu.iam.gserviceaccount.com does not have storage.objects.list access to bert_model_uncased_12."
 }
}

**Comment by IntelOSt** [comment]
Hahaha you die no identyti pic you die

**Comment by IntelOSt** [comment]
dont care kojact



Sent from my Redmi 4A
On DIAN JAKA WIDIAWAN <notifications@github.com>, May 20, 2019 12:33 PM wrote:

Hahaha you die no identyti pic you die

**Comment by IntelOSt** [comment]
See my real-time location on Maps: https://maps.app.goo.gl/3PXzv6Wqcs7BJW5g8



Sent from my Redmi 4A
