### ISSUE TITLE
OOM when allocating tensor with shape

### ISSUE THREAD

**Issue by mathshangw** [google-research/bert#1294]

**Comment by mathshangw** [comment]
is there any help please

**Comment by WilliamTambellini** [comment]
Your gpu ran out of mem. The tensor is indeed pretty big: 1393860 per 768. 
768 is a standard embedding size but why 1393860 ? vocab size ?

**Comment by mathshangw** [comment]
Thanks for replying. I used BERT to get word embedding so I make loop in the sentences I have and applied Bert for it .. I have 150000 sentences and 1393860 words

**Comment by mathshangw** [comment]
is there any help , please
