### ISSUE TITLE
Japanese voice sound mark is not an accent mark.

### ISSUE THREAD

**Issue by taku910** [google-research/bert#130]
Thank you for the great work.

It seems that multilingual models remove the Japanese [voiced sound marks (dakuten/handakuten)](https://en.wikipedia.org/wiki/Dakuten_and_handakuten) with [strip_accents](https://github.com/google-research/bert/blob/master/tokenization.py#L169) function.
These marks should not be removed. They completely change the meaning.

e.g. 
パンダ (panda) vs ハンダ (solder)
かぎ (key) vs かき(oyster)
 
In general, using NFD normalization brings lots of troubles. When tokenizing decomposed character sequence into multiple pieces, we may break the original meaning of the character.

**Comment by jacobdevlin-google** [comment]
See #138
