### ISSUE TITLE
Whitespace around Chinese characters may not keep the original intention of the sentence.

### ISSUE THREAD

**Issue by taku910** [google-research/bert#134]
Thank you for the great work.

It is a minor issue but the multilingual tokenizer puts whitespaces around Chinese characters. With this treatment, two raw text `東京` and `東 京` are considered identical, though they are not always the same.  User occasionally puts whitespace as a strong phrase/concept boundary marker.

The treatment of Chinese characters does not seem to be consistent. It would be more consistent to consider the continuous run of Chinese characters as words and force them to be segmented into characters as follows. Any thoughts?

`東京` => `東 ##京`
`東 京` => `東 京`

**Comment by jacobdevlin-google** [comment]
See #138
