### ISSUE TITLE
Korean Hangul is decomposed to Jamo (consonant/vowel chars)

### ISSUE THREAD

**Issue by taku910** [google-research/bert#135]
As the result of NFD normalization of multilingual tokenization, Korean Hangul characters are decomposed into a sequence of Jamo (consonant and vowel chars). Is this intended?

We can find several incomplete Hangul characters in the vocab (only consonant character remains).
In addition, this treatment makes the sentence longer, which might slow down the training.

**Comment by jacobdevlin-google** [comment]
See #138
