### ISSUE TITLE
Incorrect description in multilingual.md

### ISSUE THREAD

**Issue by taku910** [google-research/bert#136]
[This document](https://github.com/google-research/bert/blob/master/multilingual.md) says that:

> The only language which we had to unfortunately exclude was Thai, since it is the only language (other than Chinese) that does not use whitespace to delimit words, and it has too many characters-per-word to use character-based tokenization. Our WordPiece algorithm is quadratic with respect to the size of the input token so very long character strings do not work with it.

Japanese and Korean are also the languages that do not use whitespace for word boundary. It would be better to update this description. In addition,  to keep consistency, we might want to either 1) exclude them like Thai. 2) apply character-based segmentation like Chinese characters.

By the way, [SentencePiece](https://github.com/google/sentencepiece) algorithm is O(n). It works on very long strings.

**Comment by jacobdevlin-google** [comment]
I also updated the README to include clarify this. The new release also includes Thai.
