### ISSUE TITLE
Vowel symbols are removed from Devanagari (Hindi) scripts

### ISSUE THREAD

**Issue by taku910** [google-research/bert#138]
This is somehow related to[ this issue](https://github.com/google-research/bert/issues/130).

In Devanagari, a vowel combines with a consonant to form a compound letter. However, the current tokenizer removes some vowel symbols and only the consonant symbol remains.

Example: `कु` (k + u)   → `क ` (k,  ु is removed)

I've not checked everything, but languages in [Brahmi script family](https://en.wikipedia.org/wiki/Brahmi_script) would have the same issue.

**Comment by jacobdevlin-google** [comment]
Yes, as I mentioned in the multilingual.md the normalization may cause ambiguities in certain languages. If you are not happy with the preprocessing, you are free to train your own model in your languages of interest.
