### ISSUE TITLE
Wrong URL for SQuAD dev-v2.0.json

### ISSUE THREAD

**Issue by ymcui** [google-research/bert#141]
Hi,
The link to SQuAD dev-v2.0.json seems to be wrong with the old one.
https://github.com/google-research/bert/blob/4d4e26dc24bf78d849104e646dba422e3adba458/README.md#L452
should change to:
```
*   [dev-v2.0.json](https://rajpurkar.github.io/SQuAD-explorer/dataset/dev-v2.0.json)
```

Best,
Yiming

**Comment by jacobdevlin-google** [comment]
Thanks, this has been fixed.
