### ISSUE TITLE
how to speed up the prediction?

### ISSUE THREAD

**Issue by quincyliang** [google-research/bert#148]
The fine-tuned Chinese model is good in my task, but I found it takes around 1s to process a batch of five records (each record is 128 characters long) using CPU. Is there any suggestion to speed up the prediction? Thanks.

**Comment by xwzhong** [comment]
do you install tensorflow using bazel? it can accelerate the CPU calaulation about 3x, or maybe you can try GPU.

**Comment by hanxiao** [comment]
for faster prediction, please kindly check my [bert-as-service](https://github.com/hanxiao/bert-as-service/), which implements high-scalable non-blocking prediction for BERT.

**Comment by quincyliang** [comment]
@xwzhong  No. I just use the docker image of tensorflow.

**Comment by monanahe** [comment]
If you use tpu, TPU prediction only works on a single host (one TPU worker).
Gpu is much faster than cpu.. Maybe you can think about buy a graphic card...

**Comment by jacobdevlin-google** [comment]
BERT will always be slow on the CPU, there is not an easy way to speed it up other than to switch to GPU or TPU as suggested here.

**Comment by sibbsnb** [comment]
Why is bert prediction faster on gpu?

**Comment by Single430** [comment]
@hanxiao 
 If you can provide an example of entity recognition, it’s really good.

Thanks very much!
super.single430

**Comment by sumeet559** [comment]
@hanxiao 
Can you please share an example for predicting sentence similarity without encoding sentence.
I have fine tuned bert quora question pairs and inference is taking 1-2 seconds after export.
Can we get faster than this?

Thanks,

**Comment by sayak1711** [comment]
@xwzhong Hi. I tried building tensorflow using bazel from the official instruction. However the build runs for a long time, then throws error. Can you tell me the exact steps you followed?
