### ISSUE TITLE
how to implement the Bidirectional Transformer?

### ISSUE THREAD

**Issue by robotzheng** [google-research/bert#15]
any clues? thanks.

**Comment by ZhaoyueCheng** [comment]
It's the Transformer encoder in the Tensor2Tensor library I belive

**Comment by jacobdevlin-google** [comment]
Not sure exactly what you're asking, but the core Transformer implementation is in [modeling.py](https://github.com/google-research/bert/blob/fce885483ca05ada58462ef2931f7206796d9f76/modeling.py#L762)

Which is based on the one from tensor2tensor (but with less abstraction) and [Attention is All You Need](https://arxiv.org/abs/1706.03762)

If you're wondering how to instantiate a new instance, you can see [run_classifier.py](https://github.com/google-research/bert/blob/fce885483ca05ada58462ef2931f7206796d9f76/run_classifier.py#L389)

The Transformer is also bidirectional "by default", it requires special masking to make it unidirectional (see [here](https://github.com/openai/finetune-transformer-lm/blob/ae7e86b55254339eba3929f786b04e82602cd51d/train.py#L66) in OpenAI's transformer implementation on how that is done, although it's not needed for BERT).
