### ISSUE TITLE
Some detail about bert

### ISSUE THREAD

**Issue by mfxss** [google-research/bert#150]
Hi,
While reading your paper, I got something confused. You said your model architecture is the same as Vaswani's transformer. But Vaswani's has two parts which is an encoder in the left and an decoder. But in your figure 1. I can't tell what Trm’s inner architecture is. The encoder or decoder part?Or both.
 Does Trm stand for a real number or vector?
Thank you!

**Comment by dvector89** [comment]
BERT only has the encoder part of transformer.

**Comment by mfxss** [comment]
@dvector89 I can't understand the graph clearly.E1 stands for the vector of Word1. But what about Trm? I guess every Trm cell  outputs an vector, right? Thanks!

**Comment by dvector89** [comment]
Trm is the abbreviation of Transformation.

**Comment by jacobdevlin-google** [comment]
Yes it's almost exactly equal to the source encoder part of the original transformer. The decoder part is not used at all.
