### ISSUE TITLE
Missing data processors?

### ISSUE THREAD

**Issue by hans** [google-research/bert#152]
The BERT paper mentions fine-tuning on all sections of the dataset (including e.g. QQP, SST), but there don't seem to be data processors implemented in `run_classifier.py` for these datasets.

I can certainly re-implement these, but just wondering if I missed something? Why were these data processors not included in the release?

Thanks!

**Comment by chirag-singh** [comment]
XNLI is given instead not mentioned in the paper 😏

**Comment by chirag-singh** [comment]
Can get from here :)
https://github.com/google-research/bert/commit/a3dcf57f8bf9f5684ad768f69170175a7dbcdd08

**Comment by monanahe** [comment]
run_classifiers.py has been updated with some task processers several days ago.
May be you should update this repository~

**Comment by hans** [comment]
Got them from https://github.com/google-research/bert/commit/a3dcf57f8bf9f5684ad768f69170175a7dbcdd08 , thanks!
