### ISSUE TITLE
Something not friendly when eval the bert in run_classifier.py

### ISSUE THREAD

**Issue by Continue7777** [google-research/bert#156]
when I use my private dataset,I cannot eval when i use estimator.evaluate().I feel puzzled very much.
It took me a long time to find that,eval_batch_size must be the fator of eval_num. I think you should make Exception handling and reporting about this for those make private dataset.

**Comment by monanahe** [comment]
parameter "eval_drop_remainder" doesn't solve this?

**Comment by Continue7777** [comment]
thanks  , i still use tf-1.6.0. maybe i need to upgrade.

**Comment by monanahe** [comment]
Keep tensorflow and bert repo update-to-date 😉
( And I just astonished to find you also answered my question a few days ago....)😂😂😂
