### ISSUE TITLE
Pretrained checkpoint contains absolute path

### ISSUE THREAD

**Issue by abhishekraok** [google-research/bert#165]
The pre-trained model BERT base uncased contains checkpoint file with absolute path. It would be better to change this into relative path

model_checkpoint_path: "/usr/local/google/home/jacobdevlin/expts/bert_model_releases/uncased_L-12_H-768_A-12/bert_model.ckpt"
all_model_checkpoint_paths: "/usr/local/google/home/jacobdevlin/expts/bert_model_releases/uncased_L-12_H-768_A-12/bert_model.ckpt"

**Comment by jacobdevlin-google** [comment]
I uploaded new versions of the file while ago with this file removed. Let me know if I missed any.
