### ISSUE TITLE
Is CLS token also Masked in pre-training?

### ISSUE THREAD

**Issue by SRHyd** [google-research/bert#166]
In the BERT paper, it says
"In all of our experiments, we mask 15% of all WordPiece tokens in each sequence at random"
Is it true for CLS token also?

Thanks,
SR

**Comment by xwzhong** [comment]
no, it wouldn't https://github.com/google-research/bert/blob/master/create_pretraining_data.py#L340

**Comment by jacobdevlin-google** [comment]
Correct, it doesn't get masked.
