### ISSUE TITLE
Next sentence acc always be equals to 1 after a few training steps

### ISSUE THREAD

**Issue by zjh-nudger** [google-research/bert#180]
I pretrain bert model with smaller model size and got next sentence acc always being equals to 1 after a few training steps(5k). Some problems with my data?

**Comment by zjh-nudger** [comment]
my configuration
{
  "attention_probs_dropout_prob": 0.1, 
  "directionality": "bidi", 
  "hidden_act": "gelu", 
  "hidden_dropout_prob": 0.1, 
  "hidden_size": 128,
  "initializer_range": 0.02, 
  "intermediate_size": 128,
  "max_position_embeddings": 128,
  "num_attention_heads": 8,
  "num_hidden_layers": 3,
  "pooler_fc_size": 128,
  "pooler_num_attention_heads": 8,
  "pooler_num_fc_layers": 3, 
  "pooler_size_per_head": 64,
  "pooler_type": "first_token_transform", 
  "type_vocab_size": 2, 
  "vocab_size": 21128
}

**Comment by zjh-nudger** [comment]
I create data with `create_pretraining_data.py` use default params

**Comment by aprilvkuo** [comment]
I have the same problem when pretraining bert model.  Have you find out the resason？ @zjh-nudger

**Comment by DukeEnglish** [comment]
This is kind of not a problem now. Caz many researchers have the same phenomenon. That's also why albert change this to the order problem
