### ISSUE TITLE
Is it possible to fine-tune BERT for SQuAD-like task on another language

### ISSUE THREAD

**Issue by phateopera** [google-research/bert#202]
Hello.

The thing is, I want to apply BERT to for SQuAD-like task in another language. I have prepared a SQuAD like dataset in another language, but the problem is the dataset is too small (around 1000 question-answer pairs on 128 paragraphs). So my intuition is that i will fine-tune BERT for the English dataset, the fine-tune again for my dataset in hope that it performs well even on another language.

So my question is that can i do that on the BERT multilingual model? (i read somewhere that the multilingual model is 1 model used for many languages). If not, is there any ways for me to do that on the BERT dataset and if it is possible, is there any additional steps i have to do in order to fine-tune?

Since i am pretty new to the field, any comment or intuition would be very helpful.
Thanks

**Comment by ArlindNocaj** [comment]
Even if the pretrained model from Bert would be multilanguage, chances are low that the learnings from question and answers in english squad dataset would transfer to another language. It depends on how similar the two languages are with regard to question and answering style.

I would suggest to just take squad english and use google translate or any other translation service to derive squad like 100K dataset in your specific language. The paragraphs in squad are long enough to give reasonable results in translation. That should provide more accurate results.
