### ISSUE TITLE
How to "partially" restore from the checkpoint?

### ISSUE THREAD

**Issue by bgshin** [google-research/bert#210]
Hello, thanks for making this awesome project to the public.

I want to restore partial weights to a slightly modified model, but got an error.

```
OP_REQUIRES failed at save_restore_v2_ops.cc:184 : Not found: Key bert/MyEmbedding/LayerNorm/beta not found in checkpoint
INFO:tensorflow:Error recorded from training_loop: Restoring from checkpoint failed. This is most likely due to a Variable name or other graph key that is missing from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint. Original error:
```
In that model, some of the layer names are in the bert model checkpoint, but many of them are not (new layer). 

Any suggestion?

Thanks!

**Comment by sharpant** [comment]
Hi, I am facing a similar issue: 

When I run the below code which evaluates a model from a saved checkpoint,

```
model_fn_check = model_fn_builder2(
  bert_config=modeling.BertConfig.from_json_file(CONFIG_FILE),
  num_labels=len(label_list),
  init_checkpoint=INIT_CHECKPOINT,
  learning_rate=LEARNING_RATE,
  num_train_steps=num_train_steps,
  num_warmup_steps=num_warmup_steps,
  use_tpu=False,
  use_one_hot_embeddings=True
)

estimator_from_checkpoints = tf.estimator.Estimator(
  model_fn=model_fn_check,
  config=run_config,
  params={"batch_size": BATCH_SIZE}
)
estimator_from_checkpoints.evaluate(input_fn=valid_input_fn, steps=int(len(valid_features) / BATCH_SIZE))
```

I get the following error:

```
NotFoundError: 2 root error(s) found.
  (0) Not found: Key bert/embeddings/LayerNorm/beta not found in checkpoint
	 [[{{node save/RestoreV2}}]]
  (1) Not found: Key bert/embeddings/LayerNorm/beta not found in checkpoint
	 [[{{node save/RestoreV2}}]]
	 [[save/RestoreV2/_301]]
```
Is there a solution?

**Comment by gtgtgt1117** [comment]
> Hi, I am facing a similar issue:
> 
> When I run the below code which evaluates a model from a saved checkpoint,
> 
> ```
> model_fn_check = model_fn_builder2(
>   bert_config=modeling.BertConfig.from_json_file(CONFIG_FILE),
>   num_labels=len(label_list),
>   init_checkpoint=INIT_CHECKPOINT,
>   learning_rate=LEARNING_RATE,
>   num_train_steps=num_train_steps,
>   num_warmup_steps=num_warmup_steps,
>   use_tpu=False,
>   use_one_hot_embeddings=True
> )
> 
> estimator_from_checkpoints = tf.estimator.Estimator(
>   model_fn=model_fn_check,
>   config=run_config,
>   params={"batch_size": BATCH_SIZE}
> )
> estimator_from_checkpoints.evaluate(input_fn=valid_input_fn, steps=int(len(valid_features) / BATCH_SIZE))
> ```
> 
> I get the following error:
> 
> ```
> NotFoundError: 2 root error(s) found.
>   (0) Not found: Key bert/embeddings/LayerNorm/beta not found in checkpoint
> 	 [[{{node save/RestoreV2}}]]
>   (1) Not found: Key bert/embeddings/LayerNorm/beta not found in checkpoint
> 	 [[{{node save/RestoreV2}}]]
> 	 [[save/RestoreV2/_301]]
> ```
> 
> Is there a solution?


Did you solve this problem ？
