### ISSUE TITLE
How many word pieces is suitable for Chinese?

### ISSUE THREAD

**Issue by jiqiujia** [google-research/bert#22]
Are there any metric to measure the effect of different number of word pieces without need to train the model?

**Comment by jacobdevlin-google** [comment]
Going based on results from Neural Machine Translation, 30k-50k is a good size in almost any language. For example, the top Chinese translation system in this year's Workshop for Machine Translation used 50k WordPieces ([see section 3.4 in this paper](http://www.statmt.org/wmt18/pdf/WMT040.pdf)).

Our tokenizer is not actually suitable for Chinese (and we don't include code to learn WordPieces), but the [Google SentencePiece toolkit](https://github.com/google/sentencepiece) does have good support for Chinese.
