### ISSUE TITLE
Incorrect number of predicted examples

### ISSUE THREAD

**Issue by dilyararimovna** [google-research/bert#224]
Hello! 
I faced very strange issue. I trained classifier, and now I am trying to use `do_predict` mode.
Loading N examples for testing I am getting output file with N-1 lines.
Could you, please, check whether you are facing the same issue or not.

**Comment by jimth001** [comment]
Because some DataProcessors implemented in source code skip the first line. You can implement a new DataProcessor for your dataset or adjust the format of your data to solve this problem.

**Comment by dilyararimovna** [comment]
This issue appeared with my own preprocessor.
But yes, I just used ready `_create_examples` and didn't notice skipping the first line.
Thank you!
