### ISSUE TITLE
Need clarification for tokenizations of numbers

### ISSUE THREAD

**Issue by winston-zillow** [google-research/bert#23]
Given the tokenization is a black box, may want to have a section in the README on how it treats numbers of various forms? e.g. `12345678`, `3,456,789`, `3.1415`, `2/3`, etc.

**Comment by jacobdevlin-google** [comment]
Numbers were treated like any other token in terms of WordPiece tokenization. They were punctuation split, then split by whitespace, then tokenized inside of it. 

For example:

```
Input: 3,456,789
Punctuation split: 3 ,  456 , 789
WordPiece: 3 , 45 ##6 , 7 ##89
```
 (I didn't check whether this is the actual WordPiece) or not.
