### ISSUE TITLE
How to pad sentence A if I want fix the length of sentence A and B?

### ISSUE THREAD

**Issue by SparkJiao** [google-research/bert#315]
Hi,
I'm considering fix the length of sentence A, for example, in squad, we will construct  a `InputFeatures` by joint the tokens of query and context span as `[CLS] query [SEP] context_span_1`. And now I want to fix the length of the first part, so the length of context spans corresponding to  all queries will be same and then I can do something to any part because they have same location.
So I have a problem now, what should I do to implement this? I have tried to pad the part A by token '[PAD]' like '[SEP]' and modified the part of padding in the `input_mask` from '1' to '0' on squad and the loss can't reduce to less than 1.0. So I think the way I mask and the token for padding may have some problems, could you please give me some suggestions? Thank you very much!

**Comment by prdwb** [comment]
Hi, I am having the same issue. I was wondering if you could share your solution? Thank you!

**Comment by SparkJiao** [comment]
Padding at last to make sure the length of segment B is the same in all features may be a proper way I think. But this will cause cost more operation when you need split segment A and B.

Good luck. @prdwb
