### ISSUE TITLE
Why there is no results on SNLI dataset ?

### ISSUE THREAD

**Issue by Colanim** [google-research/bert#32]
Is there any reason why there is no BERT results on SNLI dataset, but there is for MultiNLI ?

**Comment by jacobdevlin-google** [comment]
Yeah we didn't report on it because it's not part of the GLUE eval (and also because MultiNLI generally subsumes it). I think `BERT-Base` gets about 91% and `BERT-Large` gets about 92% on it though.

**Comment by Colanim** [comment]
I fine-tuned `BERT-Base` on SNLI and got 90.686% :)

I use a single GPU (GeForce GTX 1080, 11Gb RAM), and it took approximately 5 days to fine-tune.

Awesome results..
