### ISSUE TITLE
It is the problem of shuffle. I did not shuffle my data.

### ISSUE THREAD

**Issue by NNNNNaaaaaa** [google-research/bert#324]
It is the problem of shuffle. I did not shuffle my data.

_Originally posted by @hxs91 in https://github.com/google-research/bert/issues/264#issuecomment-449802184_

I meet the same problem on chines data set, why it is due to shuffle, could you make clear?

**Comment by hxs91** [comment]
@NNNNNaaaaaa You could refer to [https://github.com/Socialbird-AILab/BERT-Classification-Tutorial/issues/11](url)
