### ISSUE TITLE
Chinese vocab contains ##word which embeddings seem meaningful as I test them in a Chinese sequence classification task?

### ISSUE THREAD

**Issue by nbcc** [google-research/bert#329]
However, embeddings of the characters (##char) seem meaningful as I test them in a Chinese sequence classification task. I want to ask how you get the embeddings of these (##char) characters. Are they just randomly initialized? Thank you!

_Originally posted by @sz128 in https://github.com/google-research/bert/issues/62#issuecomment-439272835_

**Comment by nbcc** [comment]
weight share...

**Comment by zhezh** [comment]
@nbcc  could you please elaborate it?
Is it because the embedding weight of ##word are copied from those without '##' ?
Thanks~
