### ISSUE TITLE
MultiLingual Pretraining Sampling Schedule

### ISSUE THREAD

**Issue by SinghJasdeep** [google-research/bert#331]
Dear @jacobdevlin-google 

What (if any) upsampling schedule was used when pretraining the multilingual versions of BERT. Given that the English wikipedia is substantially larger than those of other languages. 

Thank you!

**Comment by SinghJasdeep** [comment]
Sorry, mentioned in the readme: "we performed exponentially smoothed weighting of the data during pre-training data creation"

**Comment by StephennFernandes** [comment]
hey there, by any chance how could i find the implementation of "exponential smoothed weighting of the data", i need to implement this in my mT5 pre-training. couldn't find it in the codebase.
