### ISSUE TITLE
How long for training models with RTX 2080 8G 

### ISSUE THREAD

**Issue by ntson2002** [google-research/bert#365]
I got problems with out-of-memory issues when running experiments on SQUAD v1.1 (GPU config: RTX 2080 8GB). Thefore, I changed the batch_size=6, and the max_seq_length=256. Do you know the estimated time for training with 2.0 in num_train_epochs?

**Comment by bcbcbcbcbcl** [comment]
> I got problems with out-of-memory issues when running experiments on SQUAD v1.1 (GPU config: RTX 2080 8GB). Thefore, I changed the batch_size=6, and the max_seq_length=256. Do you know the estimated time for training with 2.0 in num_train_epochs?

On RTX2070, with batch_size = 8, max_seq_length = 320, num_train_epochs = 2,  it took around 2 hours 30 minutes to complete the training.

**Comment by ntson2002** [comment]
> > I got problems with out-of-memory issues when running experiments on SQUAD v1.1 (GPU config: RTX 2080 8GB). Thefore, I changed the batch_size=6, and the max_seq_length=256. Do you know the estimated time for training with 2.0 in num_train_epochs?
> 
> On RTX2070, with batch_size = 8, max_seq_length = 320, num_train_epochs = 2, it took around 2 hours 30 minutes to complete the training.

Thank you for the promptly reply

**Comment by Anton-Velikodnyy** [comment]
@bcbcbcbcbcl 
Is batch_size=8 max_seq_length = 320 the best possible for 8GB? or can we go higher with the sequence length?

**Comment by bcbcbcbcbcl** [comment]
> @bcbcbcbcbcl
> Is batch_size=8 max_seq_length = 320 the best possible for 8GB? or can we go higher with the sequence length?

With these parameters, the GPU memory usage is already near to 8GB during training. You can try decrease the batch_size if you want to try with higher sequence length or vice versa.

**Comment by rkchee** [comment]
HAve you anyone been able to get mirrored strategy to work?
