### ISSUE TITLE
How to use those three ckpt file while finetuning pre-train model using run_classifier.py?

### ISSUE THREAD

**Issue by Kryptonites** [google-research/bert#368]
Here's the parameter setting "--init_checkpoint $BERT_DIR/bert_model.ckpt ".
But, there is no file of this name in the bert-chinese zip file.

**Comment by cpmss521** [comment]
do you have any progress? @Kryptonites

**Comment by Kryptonites** [comment]
> do you have any progress? @Kryptonites

I've already finished training and testing.Thanks for asking.
