### ISSUE TITLE
Running SQuAD 1.1 on TPU encounters error

### ISSUE THREAD

**Issue by lovedavidsilva** [google-research/bert#384]
I tried to run the squad.py by following the [instruction](https://cloud.google.com/tpu/docs/tutorials/mnist) on this post and using this code (the BERT and SQuAD directories are downloaded to the same folder and set respectively):

`python run_squad.py \
  --vocab_file=$BERT_BASE_DIR/vocab.txt \
  --bert_config_file=$BERT_BASE_DIR/bert_config.json \
  --init_checkpoint=$BERT_BASE_DIR/bert_model.ckpt \
  --do_train=True \
  --train_file=$SQUAD_DIR/train-v1.1.json \
  --do_predict=True \
  --predict_file=$SQUAD_DIR/dev-v1.1.json \
  --train_batch_size=12 \
  --learning_rate=3e-5 \
  --num_train_epochs=2.0 \
  --max_seq_length=384 \
  --doc_stride=128 \
  --output_dir=$STORAGE_BUCKET/squad_base/ \
  --use_tpu=True \
  --tpu=$TPU_NAME`

I always got this error message:

 INFO:tensorflow:start_position: 113
INFO:tensorflow:end_position: 113
INFO:tensorflow:answer: einstein
INFO:tensorflow:***** Running training *****
INFO:tensorflow:  Num orig examples = 87599
INFO:tensorflow:  Num split examples = 88641
INFO:tensorflow:  Batch size = 12
INFO:tensorflow:  Num steps = 14599
INFO:tensorflow:Querying Tensorflow master () for TPU system metadata.
2019-01-22 00:14:25.871726: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
INFO:tensorflow:Failed to find TPU: _TPUSystemMetadata(num_cores=0, num_hosts=0, num_of_cores_per_host=0, topology=None, devices=[_DeviceAttributes(/job:localhost/replica:0/task:0/device:CPU:0, CPU, 268435456, 18332812683785243352), _DeviceAttributes(/job:localhost/replica:0/task:0/device:XLA_CPU:0, XLA_CPU, 17179869184, 7966451089330435898)])
INFO:tensorflow:Error recorded from training_loop: Cannot find any TPU cores in the system. Please double check Tensorflow master address and TPU worker(s). Available devices are [_DeviceAttributes(/job:localhost/replica:0/task:0/device:CPU:0, CPU, 268435456, 18332812683785243352), _DeviceAttributes(/job:localhost/replica:0/task:0/device:XLA_CPU:0, XLA_CPU, 17179869184, 7966451089330435898)].
INFO:tensorflow:training_loop marked as finished
WARNING:tensorflow:Reraising captured error
Traceback (most recent call last):
  File "run_squad.py", line 1283, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "run_squad.py", line 1215, in main
    estimator.train(input_fn=train_input_fn, max_steps=num_train_steps)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/tpu/python/tpu/tpu_estimator.py", line 2409, in train
    rendezvous.raise_errors()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/tpu/python/tpu/error_handling.py", line 128, in raise_errors
    six.reraise(typ, value, traceback)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/tpu/python/tpu/tpu_estimator.py", line 2403, in train
    saving_listeners=saving_listeners
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/estimator.py", line 351, in train
    hooks.extend(self._convert_train_steps_to_hooks(steps, max_steps))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/tpu/python/tpu/tpu_estimator.py", line 2282, in _convert_train_steps_to_hooks
    if ctx.is_running_on_cpu():
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/tpu/python/tpu/tpu_context.py", line 400, in is_running_on_cpu
    self._validate_tpu_configuration()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/tpu/python/tpu/tpu_context.py", line 586, in _validate_tpu_configuration
    'are {}.'.format(tpu_system_metadata.devices))
RuntimeError: Cannot find any TPU cores in the system. Please double check Tensorflow master address and TPU worker(s). Available devices are [_DeviceAttributes(/job:localhost/replica:0/task:0/device:CPU:0, CPU, 268435456, 18332812683785243352), _DeviceAttributes(/job:localhost/replica:0/task:0/device:XLA_CPU:0, XLA_CPU, 17179869184, 7966451089330435898)].

I also tried to put the BERT and SQuAD folders in a Google Cloud Storage Bucket and followed the answer in issue #98, but still got an error message (I am 100% sure that I used the correct folder names):

Traceback (most recent call last):
  File "run_squad.py", line 1283, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "run_squad.py", line 1129, in main
    bert_config = modeling.BertConfig.from_json_file(FLAGS.bert_config_file)
  File "/home/qiuriyi/bert/modeling.py", line 93, in from_json_file
    text = reader.read()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/lib/io/file_io.py", line 128, in read
    length = self.size() - self.tell()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/lib/io/file_io.py", line 104, in size
    return stat(self.__name).length
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/lib/io/file_io.py", line 558, in stat
    return file_statistics
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/errors_impl.py", line 528, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: Error executing an HTTP request: HTTP response code 404 with body '{
 "error": {
  "errors": [
   {
    "domain": "global",
    "reason": "notFound",
    "message": "Not Found"
   }
  ],
  "code": 404,
  "message": "Not Found"
 }
}
'
         when reading gs://mst-squad/uncased_L-24_H-1024_A-16/bert_config.json/

Has anyone successfully run the SQuAD large file on a GCP TPU and can kindly provide some guidance through this process? Thanks in advance!

**Comment by sthiruvallur** [comment]
@lovedavidsilva , How did you resolve this issue ? .  Thanks

**Comment by lovedavidsilva** [comment]
> @lovedavidsilva , How did you resolve this issue ? . Thanks

I downloaded the BERT model to my storage bucket and fixed it.

**Comment by praneethnooli** [comment]
@lovedavidsilva - I'm still facing the same issue that you had faced even after downloading the BERT model checkpoints to google storage bucket. Can you suggest me what else do I need to do in order to resolve that issue?

**Comment by saniaparveen** [comment]
I am facing the same issue while running extract_features.py script with TPUs. Any idea how to fix this? I am also using storage bucket to store the model.

**Comment by praneethnooli** [comment]
@saniaparveen - Could you add logging around use_tpu at this line of code [https://github.com/google-research/bert/blob/master/extract_features.py#L176] to check if TPU VM is connected?

**Comment by lovedavidsilva** [comment]
> @lovedavidsilva - I'm still facing the same issue that you had faced even after downloading the BERT model checkpoints to google storage bucket. Can you suggest me what else do I need to do in order to resolve that issue?

I don't remember exactly what I did. But now I just keep uploading everything to my own bucket and follow the script for the large-uncase-TPU situation. Are you still having the same errors?

**Comment by lovedavidsilva** [comment]
@saniaparveen In my case, it is very likely that the file location is not correctly defined. Other than that, I had no issue with running scripts from my own buckets.

**Comment by praneethnooli** [comment]
> I don't remember exactly what I did. But now I just keep uploading everything to my own bucket and follow the script for the large-uncase-TPU situation. Are you still having the same errors?

@lovedavidsilva - Thanks for your reply. My issue is resolved now. I was giving the wrong name for TPU with an incorrect IP address earlier, once I give the actual TPU name, my errors are resolved.
