### ISSUE TITLE
Can anyone point me in the code for the segment and position embeddings?

### ISSUE THREAD

**Issue by JoaoLages** [google-research/bert#386]
I'm referring to the embeddings of the [this](https://i.redd.it/opvkbyrf1rb21.png) picture.

**Comment by hsm207** [comment]
It's at line 185 in[ modelling.py](https://github.com/google-research/bert/blob/master/modeling.py)

**Comment by JoaoLages** [comment]
Leaving this issue open as someone (or me) might have some doubts about the implementation (which is not explained in detail in the paper)

**Comment by IntelOSt** [comment]
yes me
On Feb 6, 2019 6:44 PM, João Lages <notifications@github.com> wrote:

Leaving this issue open as someone (or me) might have some doubts about the implementation (which is not explained in detail in the paper)

**Comment by JoaoLages** [comment]
@hsm207 would you care to explain the implementation of these embeddings in detail? I.e., what are each embeddings (token, segment and position) and how they are combined? Thanks :)

**Comment by hsm207** [comment]
@JoaoLages I wrote a [blog post](https://medium.com/@_init_/why-bert-has-3-embedding-layers-and-their-implementation-details-9c261108e28a) explaining the embeddings. I hope its detailed enough :)

**Comment by JoaoLages** [comment]
@hsm207 Once again, thank you A LOT for the amazing blog post. I just have another question: BERT mentions BPE in their paper. But for what I see the embedding table is actually a lookup table, that does not deal with OOV problems. 

To my understanding, BPE is used to train the word piece embeddings. Idk if BERT retrained those embeddings previously or just used the pretrained ones in the lookup table for the token embeddings.

**Comment by hsm207** [comment]
@JoaoLages I'm glad it helped.

Where in the paper was BPE mentioned?

**Comment by JoaoLages** [comment]
Oh sorry, I was confused with the openAI GPT-2 model. All good :)
