### ISSUE TITLE
Clarification of document

### ISSUE THREAD

**Issue by jiqiujia** [google-research/bert#39]
In paper, it says
> For Wikipedia we extract only the text passages and ignore lists, tables, and headers

I wonder if these text passages extracted from a document are separated as individual documents or they are recombined to be a document?

**Comment by jacobdevlin-google** [comment]
We treat every Wikipedia article as a single document. So for example you might have two sentences in different sections of the article be considered SentenceA and SentenceB for the purposes of next sentence prediction. Although it probably doesn't matter much either way.
