### ISSUE TITLE
add a special token to never_split tuples

### ISSUE THREAD

**Issue by hahmyg** [google-research/bert#404]
In the BasicTokenizer Class, there is a keyword argument for 'never_split'
However, when I use BertTokenizer Class, it shows an Type Error

__init__() got an unexpected keyword argument 'never_split'

How can I add a special token to never_split tuples?
Such as;
never_split=("[UNK]", "[SEP]", "[PAD]", "[CLS]", "[MASK]", "MYWORD")

**Comment by hahmyg** [comment]
it solved by update

**Comment by hsm207** [comment]
@hahmyg what do you mean it got solved?

the init method of BasicTokenizer does not have a keyword argument named never_split.
