### ISSUE TITLE
Fine tuning Bert for Question answering

### ISSUE THREAD

**Issue by MathewAlexander** [google-research/bert#414]
I just wanted to ask if the weights of the Bert base model are getting updated while fine tuning Bert for Question answering. I see that the Bert for QA is a model with A linear layer on top of Bert pre-trained model. I am trying to reproduce the same model in keras. I am not able to interpret the low level tensor-flow code entirely. Could any one tell me if i should freeze the layers in the Bert base model or not?

**Comment by hsm207** [comment]
All the weights in BERT get updated during the fine tuning process.

Besides reading the code, you can check that this is the case my examining the logs that are printed. There is a section that says **** Trainable Variables **** where it lists all the weights that will get updated. For example:

![image](https://user-images.githubusercontent.com/2398765/52520393-7a528d80-2ca4-11e9-816d-c3454a9949e1.png)

Therefore, you shouldn't freeze any of the layers in BERT.

**Comment by MathewAlexander** [comment]
Thanks
