### ISSUE TITLE
Support for tied weights / Universal Transformer-like model?

### ISSUE THREAD

**Issue by matthias-samwald** [google-research/bert#42]
Tying the weights across transformer layers and thereby creating a kind of recurrent model was reported to substantially improve upon the standard transformer model across many tasks (https://arxiv.org/abs/1807.03819). It would be interesting to add support for this to BERT and see how it impacts performance.

**Comment by jacobdevlin-google** [comment]
For a variety of reasons we're not planning on making any substantial changes to this repository, so any major modeling changes would be a separate project. 

Universal Transformer is not our exact planned future direction, but with the number of people working on pre-training models inside and outside of Google I'm sure that others are planning on trying it or have already started trying it.
