### ISSUE TITLE
run_classifier_with_tfhub.py not found

### ISSUE THREAD

**Issue by GitHub30** [google-research/bert#420]
I cannot found a url for how the input preprocessing should be done to retrieve the input ids, masks, and segment ids in the following pages.

https://tfhub.dev/google/bert_cased_L-12_H-768_A-12/1
https://tfhub.dev/google/bert_uncased_L-12_H-768_A-12/1

I got 404 error when i access to https://github.com/google-research/bert/blob/master/run_classifier_with_tfhub.py

**Comment by kentonl** [comment]
This has been added in the latest commit.
