### ISSUE TITLE
ModuleNotFoundError: No module named 'modeling'

### ISSUE THREAD

**Issue by jageshmaharjan** [google-research/bert#434]
importing run_classifier from bert yields to "ModuleNotFoundError: No module named 'modeling' " error.

```
import bert
>>> from bert import run_classifier
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/maybe/bert/run_classifier.py", line 24, in <module>
    import modeling
ModuleNotFoundError: No module named 'modeling'
```
I have installed bert-tensorflow

```
(asr) maybe@maybe1:~$ pip install bert-tensorflow
Collecting bert-tensorflow
  Downloading https://files.pythonhosted.org/packages/a6/66/7eb4e8b6ea35b7cc54c322c816f976167a43019750279a8473d355800a93/bert_tensorflow-1.0.1-py2.py3-none-any.whl (67kB)
    100% |████████████████████████████████| 71kB 11.1MB/s 
Requirement already satisfied: six in ./anaconda3/envs/asr/lib/python3.6/site-packages (from bert-tensorflow)
Installing collected packages: bert-tensorflow
Successfully installed bert-tensorflow-1.0.1
```

**Comment by kentonl** [comment]
It looks like it's trying to import from the github repo source rather than the pip package.

If you are running this in a directory that contains the BERT github repo, trying running it elsewhere.

**Comment by jageshmaharjan** [comment]
Yea, exactly i figured out that. 
I created different conda environment, and now it worked. Thanks @kentonl.

**Comment by ZiranLi** [comment]
I met the same error again, and I put the git repo different with running dir but still met this error. How did you solve it?

**Comment by RahulRS406** [comment]
I am still facing the same issue with same error

**Comment by rbahumi** [comment]
@kentonl, I would like to import BERT from the repo because:
1. I want to use the latest version
2. I wan't to add my own changes.

Can you please give a few details about this error and how can we solve/bypass this issue without using the package?

**Comment by haimeil** [comment]
> Yea, exactly i figured out that.
> I created different conda environment, and now it worked. Thanks @kentonl.

hi, could you pls advise how did you fix the problem in detail? thanks in advance!

**Comment by Truth8D** [comment]
Also would like to be advised.

**Comment by RamBarankin** [comment]
Changing the working directory to the bert directory worked for me

**Comment by PalagatiDivya** [comment]
Clone the below git repo into your current working directory.
https://github.com/google-research/bert.
you can able to import modeling

**Comment by paulthemagno** [comment]
@kentonl I get this error too from pip
```python
 python3
Python 3.6.8 (default, Oct  7 2019, 12:59:55)
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import bert
>>> from bert import modeling
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'modeling'
```
