### ISSUE TITLE
How to use the QA model to do single prediction?

### ISSUE THREAD

**Issue by bcbcbcbcbcl** [google-research/bert#444]
I would like to use the trained model to do a single prediction for question answering task. Is there any reference or example? Appreciate it, thank you!

**Comment by TheGreymanShow** [comment]
Hey, 
you could check out this repo [https://github.com/huggingface/pytorch-pretrained-BERT](pretrained-bert)  

This contains a pytorch implementation for BERT-for-QA model. You just need to run the code for training it on SQUAD 1.0/2.0 datasets. Once you're done, you can easily use it for prediction. (the repo also contains the inference script which you can run by providing it your own data to see the results.)

Hope this helps.

**Comment by moh-yani** [comment]
Hello @bcbcbcbcbcl

Have you found the solution of your issue? I have a same issue with you. Could you share?

**Comment by bcbcbcbcbcl** [comment]
The easiest way would be just put 1 dataset you want to predict into the original variable/object (I can't remember) and pass to the model.

**Comment by moh-yani** [comment]
It sounds good. I will try it.


Jum, 6 Des 2019 pukul 20.31 BC <notifications@github.com> menulis:
