### ISSUE TITLE
Problem in generating the pertained output like Elmo

### ISSUE THREAD

**Issue by guoyinwang** [google-research/bert#45]
I followed the example to generate pretrained features. However, unlike other examples, it cannot find the pretrained model, with the error message like this:
`INFO:tensorflow:Could not find trained model in model_dir: /tmp/tmp6sn66z76, running initialization to predict.`.  This message print when running line `for result in estimator.predict(input_fn, yield_single_examples=True):`

However, after this, in the `model_fn` function, `tf.train.init_from_checkpoint` is called. So not sure if this actually a problem or is just a meaningless printing .

**Comment by jacobdevlin-google** [comment]
Yes that warning is expected, it just means that you didn't do any training (which is what we expect in this case).
