### ISSUE TITLE
run_squad.py only seems to use one cpu (and ignore the GPU)

### ISSUE THREAD

**Issue by bbreton3** [google-research/bert#451]
I am trying to perform the SQUAD training, but it seems to ignore the GTX1080 (although it is available to tensorflow) and run on the CPU, on a single core.

python run_squad.py \
    --vocab_file=$BERT_BASE_DIR/vocab.txt \
    --bert_config_file=$BERT_BASE_DIR/bert_config.json \
    --init_checkpoint=$BERT_BASE_DIR/bert_model.ckpt \
    --do_train=True \
    --train_file=$SQUAD_DIR/train-v2.0.json \
    --do_predict=True \
    --predict_file=$SQUAD_DIR/dev-v2.0.json \
    --train_batch_size=8 \
    --learning_rate=3e-5 \
    --num_train_epochs=1.0 \
    --max_seq_length=128 \
    --doc_stride=128 \
    --output_dir=/home/ben/Data/Bert_Models/Bert_SQUAD/ \
    --version_2_with_negative=True \
    --max_query_length 32

**Comment by WilliamTambellini** [comment]
1 make sure you installed tensorflow-gpu, not tensorflow.
2 wait few minutes : it does some preps before starting fine tuning ie real training

**Comment by bbreton3** [comment]
2. solved it. I wasn't patient enough. Thanks for your help.
