### ISSUE TITLE
How to specify max_to_keep in TPUEstimator?

### ISSUE THREAD

**Issue by danishpruthi** [google-research/bert#454]
Sorry for a noob question, I am new to TF. From what I understand, the `run_classifier.py` would only maintain the latest 5 checkpoints because of the default value of `max_to_keep` in `tf.train.Saver`, however, I am not sure how can I pass that argument through the `TPUEstimator`.

Basically, I want to keep more than 5 checkpoints.

**Comment by libertatis** [comment]
Create a [`tf.contrib.tpu.RunConfig`](https://tensorflow.google.cn/api_docs/python/tf/contrib/tpu/RunConfig) object `run_config` [run_classifier.py#L828](https://github.com/google-research/bert/blob/master/run_classifier.py#L828), set the parameter  [`keep_checkpoint_max`](https://tensorflow.google.cn/api_docs/python/tf/contrib/tpu/RunConfig#keep_checkpoint_max) to the number of checkpoints you want keep. And then pass `run_config` to the parameter 'config' of `tf.contrib.tpu.TPUEstimator` [run_classifier.py#L859](https://github.com/google-research/bert/blob/master/run_classifier.py#L859).

**Comment by danishpruthi** [comment]
Thanks a lot @libertatis. It worked like a charm. 

For folks too wondering about the same issue, the `keep_checkpoint_max` in `tf.contrib.tpu.RunConfig` is what you need to set.
