### ISSUE TITLE
Can BERT do the next-word-predict task? As it is bidirectional.

### ISSUE THREAD

**Issue by guotong1988** [google-research/bert#460]
How can we edit BERT to do the next-word-predict task?

Thank you very much!

**Comment by kyrocera** [comment]
Hey what’s the address for you guys I’m interested I wanna see you soon as you can get me some of the other stuff that you can do for me I gotta wait I’m not really sure what’s going to happen and you can do ya know how you feel better I don’t think I gotta you know you are ya girl you know I gotta was the day I wanna was a good day I wanna was a good day I wanna was a good day I wanna was a good day I wanna was the day I wanna was it a day

**Comment by indykish** [comment]
Hey did you find an answer to this problem ?

**Comment by guotong1988** [comment]
https://datascience.stackexchange.com/questions/46377/can-bert-do-the-next-word-predict-task
