### ISSUE TITLE
in the function "get_masked_lm_output", why set the output weights the same as the input embeddings?

### ISSUE THREAD

**Issue by quincyliang** [google-research/bert#47]

**Comment by jacobdevlin-google** [comment]
This is fairly standard in terms of training a language model. For one thing, OpenAI GPT also did it, and we wanted to make our model exactly comparable to theirs. But in general it's a way of significantly reducing the number of parameters while improving the results (or at least, it improves results on small LM tasks like Penn TreeBank. It probably doesn't improve results here, but it doesn't hurt and makes the number of parameters much smaller).

**Comment by guotong1988** [comment]
Same question, Thank you!
