### ISSUE TITLE
What dataset is used in Bert to pre-train non-english locale encoding?

### ISSUE THREAD

**Issue by mylyuic** [google-research/bert#470]
The paper mentioned BooksCorpus and English Wikipedia data, at which time English, i think, was the only supported language. For the later multilingual models, what pretraining datasets were used? Anyone has an idea?

thanks

**Comment by hsm207** [comment]
From[ multilingual.md](https://github.com/google-research/bert/blob/master/multilingual.md):

> The languages chosen were the top 100 languages with the largest Wikipedias. The entire Wikipedia dump for each language (excluding user and talk pages) was taken as the training data for each language

**Comment by mylyuic** [comment]
@hsm207 thanks for the pointers!
