### ISSUE TITLE
Tensor wrong shape (swag)

### ISSUE THREAD

**Issue by klxiao** [google-research/bert#479]
I tried following the instructions in [@38](https://github.com/google-research/bert/issues/38) but ran into the following bug when computing the tensors:
ValueError: Cannot reshape a tensor with 128 elements to shape [8,4] (32 elements) for 'loss/Reshape' (op: 'Reshape') with input shapes: [32,4], [2] and with input tensors computed as partial shapes: input[1] = [8,4].

To note, my input_ids/input_masks/segment_id's all have shape [4,max_seq_length], my model_fn rehapes to [32, max_seq_length], and I used the exact code for computing logits as run_classifier.py except that I reshaped logits to be [8,4], which resulted in the aforementioned error.

**Comment by klxiao** [comment]
Resolved!

**Comment by omerarshad** [comment]
@klxiao  can you please share  your code?
