### ISSUE TITLE
num_tpu_cores means number of Cloud TPUs？

### ISSUE THREAD

**Issue by guotong1988** [google-research/bert#48]
Thank you!

![image](https://user-images.githubusercontent.com/4702353/47990464-8d444780-e122-11e8-8253-03fc436e30fb.png)

![image](https://user-images.githubusercontent.com/4702353/47990368-52421400-e122-11e8-9c4b-b6614f458fc7.png)

**Comment by jacobdevlin-google** [comment]
One Cloud TPU (in terms of [a single device you rent on Google Cloud](https://cloud.google.com/tpu/docs/pricing)) has 8 cores internally. So if you're training on a single Cloud TPU from Google Cloud you should just leave this alone. For people who are training on a Cloud TPU pod (which have limited public availability at the moment), then they would want to modify this to be num_cloud_tpus*8.
