### ISSUE TITLE
How to test QA model using own input? (Single prediction question)

### ISSUE THREAD

**Issue by SSaishruthi** [google-research/bert#494]
I was able to use `run_squad.py` for dev dataset. Now, how to use it for single user question input?

**Comment by SSaishruthi** [comment]
#closed

**Comment by erichare** [comment]
Hi @SSaishruthi , have you made any progress in this? I'm trying to do the same thing, essentially "serve" the model and test it with a single input quickly.

**Comment by yiyele** [comment]
use tf_serving
