### ISSUE TITLE
xnli fin-tunining downlink invalid

### ISSUE THREAD

**Issue by yelunightroad** [google-research/bert#497]
i want test fine tuning example at https://github.com/google-research/bert/blob/master/multilingual.md, howerer the dataset download link https://s3.amazonaws.com/xnli/XNLI-1.0.zip doesn't work, where can i get the data, i download the xnli at https://github.com/facebookresearch/XNLI , it now required.

**Comment by IDIDIR** [comment]
After excavating, a live link was found in enclosed issues
https://www.nyu.edu/projects/bowman/xnli/

**Comment by yelunightroad** [comment]
> After excavating, a live link was found in enclosed issues
> https://www.nyu.edu/projects/bowman/xnli/

i've already fogot this, thank you
