### ISSUE TITLE
the date would be delayed?????

### ISSUE THREAD

**Issue by yinnxinn** [google-research/bert#5]
today is 31th OCT , please keep notified

**Comment by jimmycode** [comment]
not in all timezones LOL😀

**Comment by yinnxinn** [comment]
> not in all timezones LOL😀

emmm.. you're right , they are sleeping ...

**Comment by wykdg** [comment]
I tried to reproduce all failed, just wait for the official open source.

**Comment by Shujian2015** [comment]
Based on Settle time, we still have 18 hrs.

**Comment by jacobdevlin-google** [comment]
Just released :)
