### ISSUE TITLE
where is the XnliProcessor?

### ISSUE THREAD

**Issue by kingstarcraft** [google-research/bert#50]
I can't want run_classifier.py with Xnli dataset. I did as the CONTRIBUTING.md told. but i can't find the XnliProcessor

**Comment by jacobdevlin-google** [comment]
It's in `run_classifier.py`(https://github.com/google-research/bert/blob/ee6155110f170c1d31e09ed46a4e468a7680f063/run_classifier.py#L178). It was checked in along with the multilingual models so you'd need to sync your repo.
