### ISSUE TITLE
Poor performance on squad 2 evaluation performed outside of the GPU(s)

### ISSUE THREAD

**Issue by mfeblowitz** [google-research/bert#500]
I have noticed that a significant amount of the bert-squad 2 processing that occurs outside of the GPU (lead-up to GPU-based tf processing) occurs on a single core and can take a great deal of time.  Monitoring the GPU and CPU utilization,  I can see the GPU being inactive and a single CPU being pegged. That eventually switches to GPU usage with nearly no CPU utilization. 

I've tried profiling both my preparatory code and the bert run_squad.py code, and can only confirm that it occurs in tf. 

I am guessing that tf is executing the cpu-side code in a single thread. Also, I note that some hosts have very wimpy cores, adding even more time to the cumulative time.
Is there any user-configurable/tunable setting that can change this behavior?

**Comment by dhanaji** [comment]
Do you mean this lag is after estimators predict function is called? or before that in tf.record file preparation?

**Comment by mfeblowitz** [comment]
I'm closing this issue and opening a new one with a bigger picture.
