### ISSUE TITLE
Is this piece of code in function 'transformer_model' useless?

### ISSUE THREAD

**Issue by Traeyee** [google-research/bert#501]
In transformer_model(in modeling.py), I found one piece of code:

```
                attention_output = None
                if len(attention_heads) == 1:
                    attention_output = attention_heads[0]
                else:
                    # In the case where we have other sequences, we just concatenate
                    # them to the self-attention head before the projection.
                    attention_output = tf.concat(attention_heads, axis=-1)
```

then I searched and highlight the 'attention_output', I found that the length of attention_output is permanently 1!!! In other words, the segment of code under 'else' will be never reached. So, what is the code in the 'else' put for? Is there any intent of these codes that I can't figure out yet?

**Comment by libertatis** [comment]
I have the same question too. I wonder if the author wants to implement the stacked self attention layers.

**Comment by Leroll** [comment]
I have the same question too.

**Comment by zheyuye** [comment]
I am confused about that too

**Comment by Traeyee** [comment]
No doubt that it's useless, it's just a residual of coding

**Comment by luuhaidang** [comment]
luuhaidang-patch-10

**Comment by shuhang465** [comment]
i am confused of this question too, and i am also confused that why the BertModel takes real data as input and do all thing in the init function. When i want to reuse bert, i have to split the Bert model into init function and call fucntion, so can anyone resolve my confusion?
\s
