### ISSUE TITLE
What are the requirements of the language in order to included in the BERT?

### ISSUE THREAD

**Issue by sharavsambuu** [google-research/bert#51]
I saw there are 102 languages supported in the BERT. 
Unfortunately my native language (Mongolian language) is not supported.

Just wondering, is it because availability or size of the certain language corpus?
If so how can we help?

**Comment by rodgzilla** [comment]
In this [page](https://github.com/google-research/bert/blob/master/multilingual.md), the authors mention this: 

>The languages chosen were the top 100 languages with the largest Wikipedias.

**Comment by jacobdevlin-google** [comment]
Yes, unfortunately Mongolian is ranked 114 so it was not included.

**Comment by jacobdevlin-google** [comment]
I generated a new version of the multilingual model to fix normalization and include Thai, and I also included Mongolian in the new version. See the README for a pointer.
