### ISSUE TITLE
How to get the previous layers output of the BERT using tf_hub?

### ISSUE THREAD

**Issue by saikrishna9494** [google-research/bert#524]
I need the last 4 layers of the bert output to get the embeddings of each token. I can get those from the source code. Is there a way to get these outputs from the Tf_hub as described in the collab?

**Comment by apogiatzis** [comment]
I have the exact same question. I know you can get the token level output by using `bert_outputs["sequence_outputs"]` however I compared it with embeddings I got by summing the last 4 layers and they are different. So my question is what embeddings does "sequence_outputs" provides? Is it just the last layer?

**Comment by saikrishna9494** [comment]
It will just give the output of the last layer.

**Comment by saikrishna9494** [comment]
I have one more question, I tried to fine tune bert for sentence similarity on qoura data. Every time I run the prediction the bert model is giving different scores on the same pairs of sentences.
I am not able to understand why there is instability on prediction? Any thoughts?

**Comment by binhna** [comment]
> I have gone through your medium post on BERT embeddings. Thanks for the post.
> It will just give the output of the last layer.

Could you give the link to that post?
And btw, how could I get 4 last layers of BERT? Did you figure that out?

**Comment by saikrishna9494** [comment]
https://towardsdatascience.com/nlp-extract-contextualized-word-embeddings-from-bert-keras-tf-67ef29f60a7b

You can find the code as well in the post.
