### ISSUE TITLE
SentencePiece

### ISSUE THREAD

**Issue by loretoparisi** [google-research/bert#53]
Are you going to use [SentencePiece](https://github.com/google/sentencepiece) for **BPE** tokenization?
Thank you.

**Comment by jacobdevlin-google** [comment]
We aren't planning on changing our tokenizer. The scheme that we have works well for 102/103 languages, with the exception of Thai. (We probably should've used a modified version of SentencePiece in the first place, though).

However, for people who are training their own models on a new language, or just want to re-train from scratch with their own vocabulary, SentencePiece should work well.
