### ISSUE TITLE
AttributeError: module 'tensorflow.contrib.tpu' has no attribute 'InputPipelineConfig'

### ISSUE THREAD

**Issue by djh123** [google-research/bert#547]
AttributeError: module 'tensorflow.contrib.tpu' has no attribute 'InputPipelineConfig' 

in tensorflow-gpu==1.7

**Comment by CrookedNoob** [comment]
@djh123 How did you fix it??

**Comment by duanxingjian** [comment]
used tensorflow-gpu==1.15.2 instead and that seems to solve the issue.
