### ISSUE TITLE
Reproduce BERT-NER result

### ISSUE THREAD

**Issue by sbmaruf** [google-research/bert#581]
Is there any implementation of NER that reproduce the  `table 3` results from the https://arxiv.org/pdf/1810.04805.pdf paper?

**Comment by inessoveral** [comment]
@sbmaruf did you manage to find this?

**Comment by sbmaruf** [comment]
No, I haven't found any official TensorFlow version.
I heard that they add some document level info for BERT-NER. Without that BERT doesn't achieve SOTA. For details follow https://github.com/kamalkraj/BERT-NER/issues/1

**Comment by dsindex** [comment]
with document context to BERT, we can achieve **92.35%** (F1)
https://github.com/dsindex/ntagger/issues/4#issuecomment-810304253

**Comment by IntelOSt** [comment]
hello my friend, I have explained the Google USA developer about Google's criteria for Southeast Asia, you just have to follow the rules of the game with the original Google owner



Dikirim dari Redmi 4A saya
Pada Myungchul Shin ***@***.***>, 10 Apr 2021 10.53 AM menulis:

with document context to BERT, we can achieve 92.35% (F1)
dsindex/ntagger#4 (comment)<https://github.com/dsindex/ntagger/issues/4#issuecomment-810304253>

**Comment by sbmaruf** [comment]
Closing the issue due to inactivity.
