### ISSUE TITLE
how to generate vocab file that BERT model was trained on?

### ISSUE THREAD

**Issue by allenzhang010** [google-research/bert#59]
I was weird how to generate the vocab file when specified --vocab_file to create_pretraining_data.py?

I noticed the released BERT model indeed include the vocab file? so, how's you guy generate it via for instance, enlish Wikipedia dump file? as I am going to do the pre-training from scratch.  Appreciate your help!

Thanks,
Allen Zhang

**Comment by jacobdevlin-google** [comment]
We couldn't include that code, see [this section](https://github.com/google-research/bert#learning-a-new-wordpiece-vocabulary) of the README for alternatives.

**Comment by zihaolucky** [comment]
@allenzhang010 have you work out the solution on this?

**Comment by arunzz** [comment]
you can use this to create your vocabulary
https://github.com/kwonmha/bert-vocab-builder
