### ISSUE TITLE
how to infer in python 

### ISSUE THREAD

**Issue by jinamshah** [google-research/bert#614]
Hi all!
Before I start I would like to mention that I am very new to Tensorflow, so please pardon me if my question is very basic.
I am trying to infer BERT model after exporting it using the following piece of code:

# Export the model
def serving_input_fn():
  with tf.variable_scope("sorting_hat"):
    feature_spec = {
        "input_ids": tf.FixedLenFeature([MAX_SEQ_LENGTH], tf.int64),
        "input_mask": tf.FixedLenFeature([MAX_SEQ_LENGTH], tf.int64),
        "segment_ids": tf.FixedLenFeature([MAX_SEQ_LENGTH], tf.int64),
        "label_ids": tf.FixedLenFeature([], tf.int64),
      }
    serialized_tf_example = tf.placeholder(dtype=tf.string,
                                           shape=[None],
                                           name='input_example_tensor')
    receiver_tensors = {'examples': serialized_tf_example}
    features = tf.parse_example(serialized_tf_example, feature_spec)
    return tf.estimator.export.ServingInputReceiver(features, receiver_tensors)

EXPORT_DIR = 'gs://{}/export/{}'.format(BUCKET, TASK_VERSION)
estimator._export_to_tpu = False  # this is important
path = estimator.export_savedmodel(EXPORT_DIR, serving_input_fn)
print(path)

I want to know how can the saved model.pb file be used for inference in python code(not using the saved_model_cli )

**Comment by hsm207** [comment]
Does using [TensorFlow Serving](https://www.tensorflow.org/tfx/serving/serving_basic) work for you?

**Comment by jinamshah** [comment]
Not exactly, as i have to integrate in an application. So using a TF session and inferring on the graph would make more sense according to my application

**Comment by hsm207** [comment]
In that case, try looking at the [run_classifier.py](https://github.com/google-research/bert/blob/d66a146741588fb208450bde15aa7db143baaa69/run_classifier.py#L928-L957) script when `do_predict==True`.

**Comment by jinamshah** [comment]
Hey, in that code estimator is already loaded and is being used directly. For my case, I need to know how to use a graph.pb file and load it as the estimator to perform estimator.predict [run_classifier.py](https://github.com/google-research/bert/blob/d66a146741588fb208450bde15aa7db143baaa69/run_classifier.py#L957)

**Comment by hsm207** [comment]
It's been awhile since I last used tensorflow with a Session. I'm afraid I can't help now.

**Comment by smartcatdog** [comment]
> Does using [TensorFlow Serving](https://www.tensorflow.org/tfx/serving/serving_basic) work for you?

how to do for tensorflow-serving in online prediction ? thx

**Comment by hsm207** [comment]
@smartcatdog what do you mean online prediction?

**Comment by smartcatdog** [comment]
> @smartcatdog what do you mean online prediction?

@hsm207 online prediction is the meaning of predicting a request from web in production environment. For example, a text user input is "how do you do" from web, and then return results.

**Comment by hsm207** [comment]
@smartcatdog 
In that case, I would suggest you set up tensorflow serving and use it's rest API to send user input to it and to get the corresponding prediction. The rest api for tensorflow serving is documented [here](https://www.tensorflow.org/tfx/serving/api_rest#predict_api).

**Comment by smartcatdog** [comment]
> @smartcatdog
> In that case, I would suggest you set up tensorflow serving and use it's rest API to send user input to it and to get the corresponding prediction. The rest api for tensorflow serving is documented [here](https://www.tensorflow.org/tfx/serving/api_rest#predict_api).

@hsm207 yeah, thx ~however, i used session.run() and feed_dict when i got input by tensorflow-serving, it will take me about 300ms, it's too long to meet the online prediction just,,,,

**Comment by hsm207** [comment]
is doing the prediction on a more powerful machine an option?
