### ISSUE TITLE
650M corpus was splited to 40 files pass to create_pretraining_data, but it takes too long time

### ISSUE THREAD

**Issue by loveJasmine** [google-research/bert#616]
after 24 hours, it still runing.

python create_pretraining_data.py --input_file=BERT_BASE_DIR/all_file_merge.copyblock_notitle_linesplit.txt-6400* --output_file=BERT_BASE_DIR/tf_examples-64.tfrecord --vocab_file=chn_vocab --do_lower_case=True --max_seq_length=64 --max_predictions_per_seq=20 --masked_lm_prob=0.15 --random_seed=12345 --dupe_factor=5

all_file_merge.copyblock_notitle_linesplit.txt-6400* is all_file_merge.copyblock_notitle_linesplit.txt-640001 to all_file_merge.copyblock_notitle_linesplit.txt-640039

each file less than 20M

**Comment by jrc2139** [comment]
are you using tensorflow-gpu?  it was taking forever to do one iteration on my laptop with a 5Gb corpus with splits of ~250MB.  Tried it on my desktop with a 1080ti and it took around 20 hours to do the whole corpus and yielded a ~42GB tr.record!

**Comment by loveJasmine** [comment]
how to use GPU to run create_pretraining_data.py

**Comment by jrc2139** [comment]
i actually think i'm wrong about that.  it's probably the fact that my desktop has much more ram and a better cpu.
