### ISSUE TITLE
Bert Context Based QA

### ISSUE THREAD

**Issue by rohan636** [google-research/bert#620]
Very new to NLP, still learning at the moment. Could I get a little guidance understanding on how to implement a context-based QA system with gives results in natural language?

Example: 
Context: Its 7pm in New York. 
Question: What is the time in New York?
Answer: Its 7 in the evening in New York

**Comment by saurabh-tripathi** [comment]
I think it gives answer from the context. It gives the start and end index of the answer. You can go through the readme file, especially through the section SQuAD 2.0
