### ISSUE TITLE
Not able to run BERT-Large with either SQuAD 2.0/SQuAD 1.1 on GCP with TPU

### ISSUE THREAD

**Issue by praneethnooli** [google-research/bert#628]
Hello, I am new to GCP and I followed the instructions of mnist training in https://cloud.google.com/tpu/docs/tutorials/mnist to run run_squad.py with SQuAD 2.0 in my vm with the following script:

python run_squad.py
  --vocab_file=${STORAGE_BUCKET}/BERT_LARGE_DIR/vocab.txt \
  --bert_config_file=${STORAGE_BUCKET}/BERT_LARGE_DIR/bert_config.json \
  --init_checkpoint=${STORAGE_BUCKET}/BERT_LARGE_DIR/bert_model.ckpt \
  --do_train=True \
  --train_file=${STORAGE_BUCKET}/SQUAD_DIR/train-v2.0.json \
  --do_predict=True \
  --predict_file=${STORAGE_BUCKET}/SQUAD_DIR/dev-v2.0.json \
  --train_batch_size=24 \
  --learning_rate=3e-5 \
  --num_train_epochs=2.0 \
  --max_seq_length=384 \
  --doc_stride=128 \
  --output_dir=${STORAGE_BUCKET}/result/ \
  --use_tpu=True \
  --tpu_name=$TPU_NAME \
  --version_2_with_negative=True

but I always end up with the following issue after executing the script for some time

RuntimeError: Cannot find any TPU cores in the system. Please double check Tensorflow master address and TPU worker(s). Available devices are 
[_DeviceAttributes(/job:localhost/replica:0/task:0/device:CPU:0, CPU, 268435456, 12323948552096263132), _DeviceAttributes(/job:localhost/replica:0/t
ask:0/device:XLA_CPU:0, XLA_CPU, 17179869184, 12521347734421362015)].

**I'm facing the same issue even if I run BERT-Large with SQuAD 1.1**

I don't know if I'm missing anything, can anyone please help me out. 
Thanks in advance!

**Comment by saberkun** [comment]
Can you paste more logs from your vm?
Could you add logging around TPUResolver to check if TPU VM is connected?
Note that if you know your TPU VM ip address, you can put it as --master=ip address too.

**Comment by praneethnooli** [comment]
@saberkun - As suggested by you, I had put my TPU master address and then added logging around TPUResolver and figured out that TPU VM is not connected. I tried logging the values of FLAGS.use_tpu and FLAGS.tpu_name but I always get the error saying "TypeError: not all arguments converted during string formatting". I believe somehow there is an issue with FLAGS.
I even tried commenting 1139 line - **if FLAGS.use_tpu and FLAGS.tpu_name:** to bypass the condition but then I'm getting "ValueError: Both master and cluster are set." I'm even new to TensorFlow, can you please suggest me how should I proceed forward.

**Comment by saberkun** [comment]
tf.logging.info(str(FLAGS. use_tpu)) should work.
Please read this code to check your situation: https://github.com/tensorflow/estimator/blob/master/tensorflow_estimator/python/estimator/tpu/tpu_config.py#L227
Could you first verify from your gcp console that you have your TPU VM live? Thx

**Comment by praneethnooli** [comment]
Thank you so much @saberkun for all your suggestions. The problem was with the way how I'm assigning the parameter tpu_name. I was giving the wrong IP address URL. If I give the exact TPU name, it's working fine now.

If I have a custom question and answer dataset, do you have any suggestions on how do I train the model, can I keep the initial checkpoint to the one that was obtained after fine-tuning with SQuAD 2.0 and then fine tune to my custom question and answers?

**Comment by IntelOSt** [comment]
make Iyes Glas Hologra could consept ....?



Sent from my Redmi 4A
On praneethnooli <notifications@github.com>, May 17, 2019 10:14 PM wrote:

Closed #628<https://github.com/google-research/bert/issues/628>.
