### ISSUE TITLE
How do I continue training from checkpoint?

### ISSUE THREAD

**Issue by kkkppp** [google-research/bert#632]
I did initial fine-tuning, created checkpoint, in my case it's model.ckpt-838
Then I created new dataset from incorrect predictions, annotated by user

Now I want to continue fine-tuning from where I stopped on first attempt
So I run run_classifier with value --init_checkpoint=./output/result_dir/model.ckpt-838

However It doesn't do what I expected:

INFO:tensorflow:***** Running training*****
INFO:tensorflow:  Num examples = 10
INFO:tensorflow:  Batch size = 24
INFO:tensorflow:  Num steps = 4
INFO:tensorflow:Skipping training since max_steps has already saved.

What is correct way to resume training?

**Comment by kkkppp** [comment]
It seems that it's more Tensorflow question, changing max_steps to steps in the line below allows incremental training. However it would be helpful for novices like me to have this described somewhere in docs.  

>>>    estimator.train(input_fn=train_input_fn, max_steps=num_train_steps)

**Comment by lbda1** [comment]
when continue training use these two parameters.
--init_checkpoint=old_model_dir\
--output_dir=new_model_dir \

**Comment by lbda1** [comment]
> It seems that it's more Tensorflow question, changing max_steps to steps in the line below allows incremental training. However it would be helpful for novices like me to have this described somewhere in docs.
> 
> > > > estimator.train(input_fn=train_input_fn, max_steps=num_train_steps)

What does this mean?
