### ISSUE TITLE
Padding sent1 hurts the performance of sentence pair tasks

### ISSUE THREAD

**Issue by Akella17** [google-research/bert#635]
Padding the first sentence to make it a fixed-sized vector hurts the accuracy of sentence pair tasks. My input representation for BERT is as follows,
```python
Input_ids   : <CLS><...Sent_1_tokens...><SEP><PAD>...<PAD> | <SEP><...Sent_2_tokens...><SEP><PAD>...<PAD>
Segment Ids :  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 | 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0
Input Mask  :  1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 | 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0
```
When I do not pad **sent1** and directly append it with a **separator token** followed by **sent2** (as suggested in the paper), I am getting great accuracy score. However, the inputs to BERT for my specific usecase are already padded, which puts me in a tough spot. Is there any reason why fine tuning might not be working for this representation and can you suggest a solution to this problem?

**Comment by Akella17** [comment]
Never mind, resolved this issue!!

To those who might be stuck in a similar issue, replace the [PAD] tokens between sentence 1 and sentence 2 with [unused<num>] tokens from BERT's **vocab.txt** file. I am guessing that the reason this works is that the [PAD] tokens between sentence 1 and sentence 2 represents a slightly different meaning as opposed to the original [PAD] tokens used during BERT's training (which generally comes at the end of input sequence, hinting the network to not waste any attention to what follows beyond). Using an  [unused<num>] token helps BERT learn a meaningful embedding for the [PAD] present between sentences while also focussing on achieving the objective of the training simultaneously. It is actually awesome how seamlessly BERT does it.

**Comment by Akella17** [comment]
A more elegant solution is to use the **input_mask** to mask the [PAD] tokens between the sentence pair. **Note:** The *input_length* is computed as the distance from the start before encountering the first token (which in my case occurred in between the sentence pair). If you are following my procedure then you must also explicitly adjust the *input_length* tensor, else the implicit masking in Bert would mask anything that comes after the first [PAD] token.

**Comment by PeterPanUnderhill** [comment]
> A more elegant solution is to use the **input_mask** to mask the [PAD] tokens between the sentence pair. **Note:** The _input_length_ is computed as the distance from the start before encountering the first token (which in my case occurred in between the sentence pair). If you are following my procedure then you must also explicitly adjust the _input_length_ tensor, else the implicit masking in Bert would mask anything that comes after the first [PAD] token.

Hi what do you mean by input_length? I couldn't find any code related to it.

**Comment by cooelf** [comment]
> 
> 
> A more elegant solution is to use the **input_mask** to mask the [PAD] tokens between the sentence pair. **Note:** The _input_length_ is computed as the distance from the start before encountering the first token (which in my case occurred in between the sentence pair). If you are following my procedure then you must also explicitly adjust the _input_length_ tensor, else the implicit masking in Bert would mask anything that comes after the first [PAD] token.

Thanks for sharing your solution. I have encountered the same issue. But I am quite confused about what you mean about using the **input_mask** to mask the [PAD] tokens between the sentence pair. Can you share the exact modifications?
