### ISSUE TITLE
How are out of vocabulary words handled for Chinese?

### ISSUE THREAD

**Issue by liweitj47** [google-research/bert#65]
I understand there may not exist OOV or UNK problem when using word piece, but how are the OOV characters handled for Chinese? Are they mapped to [UNK]? I was not able to find such operations in the tokenization.py file.

**Comment by jacobdevlin-google** [comment]
The top 8000 characters are character-tokenized, other characters are mapped to [UNK]. I should've commented this section better but [it's here](https://github.com/google-research/bert/blob/e13c1f3459cc254f7abbabfc5a286a3304d573e4/tokenization.py#L292)
