### ISSUE TITLE
Not compatible with tensorflow 2.0

### ISSUE THREAD

**Issue by makaveli10** [google-research/bert#674]
Is Bert not compatible with tensorflow 2.0 ?

AttributeError                            Traceback (most recent call last)
<ipython-input-4-1b957e7a053a> in <module>()
      1 import modeling
----> 2 import optimization
      3 import run_classifier
      4 import run_classifier_with_tfhub
      5 import tokenization
/content/bert_repo/optimization.py in <module>()
     85 
     86 
---> 87 class AdamWeightDecayOptimizer(tf.train.Optimizer):
     88   """A basic Adam optimizer that includes "correct" L2 weight decay."""
     89 

AttributeError: module 'tensorflow._api.v2.train' has no attribute 'Optimizer'

**Comment by kpe** [comment]
If you need TF 2.0 support, there are different Keras implementation out there - you could check mine at [kpe/bert-for-tf2](https://github.com/kpe/bert-for-tf2).

**Comment by saberkun** [comment]
Work in progress but not fully ready: https://github.com/tensorflow/models/tree/master/official/bert

**Comment by makaveli10** [comment]
> Work in progress but not fully ready: https://github.com/tensorflow/models/tree/master/official/bert

Thanks!

**Comment by bwindsor22** [comment]
New link is https://github.com/tensorflow/models/tree/master/official/nlp/bert

**Comment by sbose94** [comment]
Can someone please explain to me in simple terms what do I need to include in the code to avoid getting this error : "AttributeError: module 'tensorflow._api.v2.train' has no attribute 'Optimizer' " ?
