### ISSUE TITLE
Can Bert be fine-tuned on unlabeled data?

### ISSUE THREAD

**Issue by Wanjun0511** [google-research/bert#682]
Elmo can fine tune on unlabeled data, so we might need less domain labeled data to do training.  So is it possible on Bert?  Do you think it's a useful way to make model focus on domain data? 

![image](https://user-images.githubusercontent.com/19729970/59005663-0a6aa300-8851-11e9-8aed-0704ec2ad845.png)

**Comment by pren1** [comment]
If I understand you correctly, this is the answer...This tuning process is called "pre-training" in Bert...

https://github.com/google-research/bert#pre-training-with-bert

**Comment by Wanjun0511** [comment]
@pren1  Yes that's what I want.  Thank u so much.

**Comment by biuleung** [comment]
@Wanjun0511 @pren1 
I did a pre training process for the model and I got a checkpoint, graph.phtxt and series of model.ckpt checkpoint files, so everything was fine for the pre training proccess.
And the next step, I am now trying to fine tune the self pre training model but I am encountering some error messages (the main part of the error messages shown below):
---------------------------------------------------------------------------------------
2 root error(s) found.
  (0) Not found: Key output_bias not found in checkpoint
	 [[node save/RestoreV2 (defined at run_classifier.py:953) ]]
	 [[save/RestoreV2/_301]]
  (1) Not found: Key output_bias not found in checkpoint
	 [[node save/RestoreV2 (defined at run_classifier.py:953) ]]
0 successful operations.
0 derived errors ignored.

Original stack trace for 'save/RestoreV2':
  File "run_classifier.py", line 1054, in <module>
    tf.app.run() 
------------------------------------------------------------------------------
Have you met the situation like this? I have no idea how to fix it.
I will be grateful for any help you can provide.
