### ISSUE TITLE
Interpretation of fine tuning output

### ISSUE THREAD

**Issue by optstat** [google-research/bert#694]
I am fine tuning BERT large model on a CPU with 20 cores Xeon v2 processor with 96 GB of ram.  My GPU is a Titan Z with only 6GB memory so it is not suitable for the large model.  I am aware that this will take a long time to train.  The options I used are as follows
export BERT_LARGE_DIR=/home/panos/Dropbox/SENSEE/Google-Bert/model/cased_L-24_H-1024_A-16
export SQUAD_DIR=/home/panos/Dropbox/SENSEE/Google-Bert/use_cases/squad

python3 run_squad.py \
  --vocab_file=$BERT_LARGE_DIR/vocab.txt \
  --bert_config_file=$BERT_LARGE_DIR/bert_config.json \
  --init_checkpoint=$BERT_LARGE_DIR/bert_model.ckpt \
  --do_train=True \
  --train_file=$SQUAD_DIR/train-v2.0.json \
  --do_predict=True \
  --predict_file=$SQUAD_DIR/dev-v2.0.json \
  --train_batch_size=24 \
  --learning_rate=3e-5 \
  --num_train_epochs=2.0 \
  --max_seq_length=384 \
  --doc_stride=128 \
  --do_lower_case=False \
  --version_2_with_negative True \
  --output_dir=/home/panos/Dropbox/SENSEE/Google-Bert/use_cases/learn\
  --use_tpu=False 

My question is how to interpret the output.  Here are the last few lines 
INFO:tensorflow:Saving checkpoints for 2000 into /home/panos/Dropbox/SENSEE/Google-Bert/use_cases/learn/model.ckpt.
INFO:tensorflow:global_step/sec: 0.00791887
INFO:tensorflow:examples/sec: 0.190053
INFO:tensorflow:global_step/sec: 0.00797603
INFO:tensorflow:examples/sec: 0.191425
zINFO:tensorflow:global_step/sec: 0.00796088
INFO:tensorflow:examples/sec: 0.191061
How do I know how far the training has progresses as a fraction of the total?  Is the number 2000 above refer to the number of steps taken so far?  If so how many total steps are there?

Many thanks!
--Panos

**Comment by starspringcloud** [comment]
I have the same question

**Comment by optstat** [comment]
Here is what I have determined in case other people have the same issue.  While training one of the output lines is the total number of steps, namely:
INFO:tensorflow:  Num steps = 10859
Locate this number and copy it.  You then need to find the output that gives you the mean number of global steps per  second, for example
INFO:tensorflow:global_step/sec: 0.02
So the estimated execution time is Num steps/(global_step/sec)
The unit is second so convert that to hours or days.
