### ISSUE TITLE
End to End (Fine-tuning + Predicting) with Cloud TPU has issu

### ISSUE THREAD

**Issue by foye501** [google-research/bert#696]
InvalidArgumentError: Error executing an HTTP request: HTTP response code 400 with body '{
 "error": {
  "errors": [
   {
    "domain": "global",
    "reason": "invalid",
    "message": "Invalid bucket name: 'YOUR_BUCKET'"
   }
  ],
  "code": 400,
  "message": "Invalid bucket name: 'YOUR_BUCKET'"
 }
}
'
	 when reading metadata of gs://YOUR_BUCKET/bert-tfhub/models/MRPC

**Comment by LaurenceTews** [comment]
You need to replace YOUR_BUCKET with the actual name of your GCS bucket that you should have created. That bucket should contain the BERT pre-trained model files.

**Comment by ArtificialZeng** [comment]
> You need to replace YOUR_BUCKET with the actual name of your GCS bucket that you should have created. That bucket should contain the BERT pre-trained model files.

how do I kown my bucket name??

**Comment by foye501** [comment]
OK，I got it  thanks
