### ISSUE TITLE
Docs: Very wrong assertion that Wikipedia size correlates with number of speakers

### ISSUE THREAD

**Issue by brendano** [google-research/bert#760]
Currently `bert/multilingual.md` states:

"... the size of the Wikipedia for a given language varies greatly, and therefore low-resource languages may be "under-represented" in terms of the neural network model ...
However, the size of a Wikipedia also correlates with the number of speakers of a language"

This claim is wrong. For example, Hindi and English have roughly the same number of native speakers (300-400M?), but Hindi Wikipedia is 40x smaller than English Wikipedia.  Even if there is a correlation (do the BERT authors have any evidence of this?), it's a weak enough correlation to miss out on a resource issue for one of the most widely spoken languages in the world.

The size of a language's Wikipedia may be dependent on many other factors, including historical sociopolitical and institutional power, history of colonization and imperialism, etc. It's naive and anti-egalitarian to assume  technical/linguistic resources already exist in proportion to social good.

This assertion is additionally disappointing since it's used to excuse possible weaknesses in the model for low-resource languages, implying an assumption that it's OK to screw over speakers of rare languages. But even if you think so, the uneven distribution of Wikipedia sizes can cause a model to fail to serve massive portions of humanity.

**Comment by bittlingmayer** [comment]
Ey chico, technically it does correlate, but this is GitHub, just send a pull request

**Comment by stefan-it** [comment]
@brendano I totally agree with you. Let's have a look at [List of languages by total number of speakers (Wikipedia)](https://en.wikipedia.org/wiki/List_of_languages_by_total_number_of_speakers).

| Rank (by number of Wikipedia articles) | Language | Number of articles | Total number of speakers
| 76 | Telugu | 70,908 | 93
| 78 | Bengali | 69,917 | 265 (!)  
| 83 | Javanese | 56,328 | 68.2
| 86 | Marathi | 53,785 | 95.3
| 88 | Swahili | 51,859 | 98.3
| 92 | Western Punjabi | 47,944 | 92.7

Bengali is ranked as the 7th most spoken languages, but has ~ 70K Wikipedia articles.

Gujarati has only 28,513 articles (not even in the 100 Wikipedia list) and 60,5 million speakers. Hausa is also not in the Top 100 list and has only 3,663 articles and 63.4 million speakers.

Btw. I can hardly understand "West Frisian" (and the total number of speakers is less than a million), and it has 42,455 Wikipedia articles (making it into the Top 100 list) ;)

**Comment by slavpetrov** [comment]
Thanks Brendan for pointing this out. 

I updated the description to remove the claim:
https://github.com/google-research/bert/pull/764

Apologies if I didn't use GitHub properly.
