### ISSUE TITLE
how to run multiple run_classifier.py programs at the same time

### ISSUE THREAD

**Issue by HsiaYu** [google-research/bert#781]
When I try to run more than one run_classifier.py program, I get error as follows:

E0721 15:11:25.969784 140338394945280 error_handling.py:70] Error recorded from training_loop: truncated record at 12582736
	 [[node IteratorGetNext (defined at run_classifier.py:922) ]]

Original stack trace for 'IteratorGetNext':
  File "run_classifier.py", line 1023, in <module>

**Comment by marcoaleixo** [comment]
any news about this?
