### ISSUE TITLE
run_classifier.py input_fn required edits for large datasets

### ISSUE THREAD

**Issue by mukhinv** [google-research/bert#796]
I am trying to run BERT on a custom large set of data (~1 million rows). I am not running BERT on TPU, but rather a K80. I seem to get the following error after building the estimator object and calling train on it:

> Traceback (most recent call last):
>   File "/projects/p30412/incidentals-vlad/bert_quest.py", line 257, in <module>
>     estimator.train(input_fn=train_input_fn, max_steps=num_train_steps)
>   File "/projects/p30412/python-venvs/vlad_DL_36/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 354, in train
>     loss = self._train_model(input_fn, hooks, saving_listeners)
>   File "/projects/p30412/python-venvs/vlad_DL_36/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 1207, in _train_model
>     return self._train_model_default(input_fn, hooks, saving_listeners)
>   File "/projects/p30412/python-venvs/vlad_DL_36/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 1234, in _train_model_default
>     input_fn, model_fn_lib.ModeKeys.TRAIN))
>   File "/projects/p30412/python-venvs/vlad_DL_36/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 1075, in _get_features_and_labels_from_input_fn
>     self._call_input_fn(input_fn, mode))
>   File "/projects/p30412/python-venvs/vlad_DL_36/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 1162, in _call_input_fn
>     return input_fn(**kwargs)
>   File "/projects/p30412/python-venvs/vlad_DL_36/lib/python3.6/site-packages/bert/run_classifier.py", line 740, in input_fn
>     dtype=tf.int32),
>   File "/projects/p30412/python-venvs/vlad_DL_36/lib/python3.6/site-packages/tensorflow/python/framework/constant_op.py", line 208, in constant
>     value, dtype=dtype, shape=shape, verify_shape=verify_shape))
>   File "/projects/p30412/python-venvs/vlad_DL_36/lib/python3.6/site-packages/tensorflow/python/framework/tensor_util.py", line 497, in make_tensor_proto
>     (shape_size, nparray.size))
> ValueError: Too many elements provided. Needed at most 174662400, but received 272910000

Here is what estimator object is:

> run_config = tf.estimator.RunConfig(
>     model_dir=OUTPUT_DIR,
>     save_summary_steps=SAVE_SUMMARY_STEPS,
>     save_checkpoints_steps=SAVE_CHECKPOINTS_STEPS)
> 
> model_fn = model_fn_builder(
>   num_labels=len(label_list),
>   learning_rate=LEARNING_RATE,
>   num_train_steps=num_train_steps,
>   num_warmup_steps=num_warmup_steps)
> 
> estimator = tf.estimator.Estimator(
>   model_fn=model_fn,
>   config=run_config,
>   params={"batch_size": BATCH_SIZE})

train_input_fn is the input_fn_builder output from the run_classifier.py in this repo.

After digging through the source code to find the issue, I have found the following in the run_classifier.py input_fn (lines 733-755):

`    # This is for demo purposes and does NOT scale to large data sets. We do
    # not use Dataset.from_generator() because that uses tf.py_func which is
    # not TPU compatible. The right way to load data is with TFRecordReader.`

I assume the error is exactly because tf.data.Dataset.from_tensor_slices() is used in the input_fn(). Could you please provide instructions on what should I change in the source code of input_fn for it to work with an output of input_fn_builder so that it scales to large datasets? I tried searching for this but was not able to find an answer to this. 

Thanks!

**Comment by guruvasuraj** [comment]
Hi @mukhinv,
                       I ran into the same issue a couple of days ago. Were you able to find a fix? If so, could you please share the steps?

Thanks,
Guru.

**Comment by mukhinv** [comment]
Hi @guruvasuraj 

I was able to solve this by using a different input function in the run_classifier.py - I believe it was file_based_input_fn_builder() alongside other file_based functions. However, I have since moved on to using the [pytorch-transformers](https://github.com/huggingface/pytorch-transformers) implementation of BERT since I personally find it more convenient to work with.

Thanks,
Vlad
