### ISSUE TITLE
Exporting best model

### ISSUE THREAD

**Issue by smr97** [google-research/bert#833]
Hi, I am serving a  BERT model. My constraint is that I want to export the model with the best accuracy on the evaluation dataset. I want to do this automatically (using the BestExporter class from TF). However, the problem is that this repository uses the TPUEstimator API, which does not allow me to pass in this BestExporter object.

I tried to work around by passing in the estimator object in the BestExporter call to export(), but this somehow does not work. There is no error, but I get no output in the export_dir path that I give to my BestExporter object.

Can someone please help?

**Comment by sarnikowski** [comment]
Check out issue #817

**Comment by smr97** [comment]
Thanks, I actually looked at @IvanUkhov's wrapper around BestExporter class, and called the `export` function on this separately (after the `estimator.eval()` call). This works well, and I can export the best model pretty easily. The default is to compare loss, which threw me off balance since I was expecting it to be accuracy 😬. 

I guess the issue is closed for my use-case. It would be nice to have an official example or a documentation line regarding the inter-operability of the `Exporter` API with the `Estimator` API. Specifically when one does not use the `train_and_eval` call.

**Comment by Nidhi-kumari** [comment]
can you please share the changes you have made in the code to get the best model.

**Comment by smr97** [comment]
@Nidhi-kumari here you go https://github.com/tensorflow/tensorflow/issues/8658#issuecomment-468815319
