### ISSUE TITLE
How to run bert classifier pb file 

### ISSUE THREAD

**Issue by anmol4210** [google-research/bert#848]
Hi,
I am trying to run bert classifier. I have fine tuned the model on my data. I have also converted ckpt files to pb files. Now I want to do predictions using this pb files. Could anyone guide me how can I do it. What changes do I have to make in the code to load pb file instead of the ckpt files. Any help would be great.

**Comment by gyshi** [comment]
> files to pb files. Now I want to do predictions using this pb files. Could anyone guide me how can I do it. What changes do I have to make in the code to load pb file instead of the ckpt files. Any help would be great.

do you have solved it？ i think use frezon.py file （in tensorflow/tools/ ) to solve it, i want to know you answer. thx.

**Comment by WillLiGitHub** [comment]
click this link: https://github.com/yajian/bert/blob/master/model_exporter.py
