### ISSUE TITLE
mask 15% words in random?

### ISSUE THREAD

**Issue by quincyliang** [google-research/bert#85]
Have you try other parameters like making 25% of words? How do you come up those magic parameters? The same as 10% of time to keep word unchanged. thanks.

**Comment by jacobdevlin-google** [comment]
We didn't try a lot of ablation on this. Those numbers are just what made sense to me and the only thing that I tried. It's possible that other values will work better (or more likely, the system isn't very sensitive to the exact hyperparameters).
