### ISSUE TITLE
Plan to have a FP16 flag for GPU that can save the memory usage ?

### ISSUE THREAD

**Issue by howardhsu** [google-research/bert#88]
Is there a plan to have a FP16 version of tuning so to double the virtual memory of GPU to allow for larger batch size or longer texts ?

**Comment by jacobdevlin-google** [comment]
We probably wont add support for this to the main repository because it will add substantial complexity and only a limited number of GPUs can take advantage of it. Someone is welcome to fork it and add support if they want.
