### ISSUE TITLE
Can not run Bert with Colab TPU

### ISSUE THREAD

**Issue by nhocqn** [google-research/bert#881]
I try to upload credentials to TPU
`  with open('/content/adc.json', 'r') as f:
    auth_info = json.load(f)
  tf.contrib.cloud.configure_gcs(session, credentials=auth_info)
`
I got this error :
> InternalError: From /job:tpu_worker/replica:0/task:0:
> The filesystem registered under the 'gs://' scheme was not a tensorflow::RetryingGcsFileSystem*.
> 	 [[{{node GcsConfigureCredentials}}]]
> 
> During handling of the above exception, another exception occurred:
> 
> InternalError                             Traceback (most recent call last)
> /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/client/session.py in _do_call(self, fn, *args)
>    1382                     '\nsession_config.graph_options.rewrite_options.'
>    1383                     'disable_meta_optimizer = True')
> -> 1384       raise type(e)(node_def, op, message)
>    1385

**Comment by KimBue** [comment]
I got the same thing. Yesterday it still worked. Is it possible google changed something in colab?

**Comment by WissamAntoun** [comment]
I got the same thing when I tried authenticating my google cloud storage account with a TPU instance, but when I switched to a GPU based-one it worked fine

**Comment by nhocqn** [comment]
go to Cloud IAM  and try to grand permission for TPU service account manually or use gsutil command . it works .
Here is the free TPU service account email :

> service-495559152420@cloud-tpu.iam.gserviceaccount.com
