### ISSUE TITLE
How many "num_tpu_cores" be set ? 

### ISSUE THREAD

**Issue by rmard90** [google-research/bert#885]
I try to pretraining with **run_pretraining.py** using **tpu-v2-32**
How many "num_tpu_cores" be set ? 
When tested with tpu-v2-8 worked fine(num_tpu_cores=8).

python3 run_pretraining.py \ 
  --input_file=gs://... \
  --output_dir=gs://... \
  --do_train=True \
  --do_eval=True \
  --bert_config_file=/data/workspace/bert/bert_config.json \
  --train_batch_size=64 \
  --max_seq_length=128 \
  --max_predictions_per_seq=19 \
  --num_train_steps=100 \
  --num_warmup_steps=70 \
  --learning_rate=1e-4 \
  --use_tpu=True \
  --num_tpu_cores=32 \
  --tpu_name=grpc://ip:8470 \
  --tpu_zone=us-central1-a \
  --gcp_project=myproject

**This are parameters to run. Is that correct? When i do this, i got an error like this :** 

ValueError: TPUConfig.num_shards is not set correctly. According to TPU system metadata for Tensorflow master (grpc://...:8470): num_replicas should be (8), got (32). For non-model-parallelism, num_replicas should be the total num of TPU cores in the system. For model-parallelism, the total number of TPU cores should be num_cores_per_replica * num_replicas. Please set it accordingly or leave it as `None`

**When i set "num_tpu_cores=8", I got the following error :**

I1025 05:22:42.688320 140065835681600 tpu_estimator.py:557] Init TPU system
ERROR:tensorflow:Error recorded from evaluation_loop: From /job:worker/replica:0/task:0:
Cloud TPU: Invalid TPU configuration, ensure ClusterResolver is passed to tpu.RunConfig
         [[{{node configure_distributed_tpu/_0}}]]

Am I missing something else? Or which one should I set?

**Comment by rmard90** [comment]
I solved. For TPU Pods you must use the TPU name. not IP address.
--tpu_name = grpc://my.tpu.ip:8470 (X)
--tpu_name = mytpu_name (O)

**Comment by dhuy237** [comment]
@rmard90 Can you please tell me where can I get the `tpu_name`?
