### ISSUE TITLE
"model_fn should return an EstimatorSpec." Error when running "predicting_movie_reviews_with_bert_on_tf_hub.ipynb" for fine-tuning BERT-Chinese Model

### ISSUE THREAD

**Issue by xinxu75** [google-research/bert#889]
I tried to run "predicting_movie_reviews_with_bert_on_tf_hub.ipynb", but fine-tuning on a Chinese-text csv with corresponding labels. As such I loaded 'https://tfhub.dev/google/bert_chinese_L-12_H-768_A-12/1' model instead of English-model in the original code

I only made minimum changes from the original jpynb for data preparation, which was running OK. But during training as in 
estimator.train(input_fn=train_input_fn, max_steps=num_train_steps)
there was an error of "ValueError: model_fn should return an EstimatorSpec." - Note that I didn't make any modification in model_fn_builder(num_labels, learning_rate, num_train_steps, num_warmup_steps)

The full error log is as follows - it was running on CPU (8GB RAM) with Windows 10 environment:  
Traceback (most recent call last):
  File "bert_classify.py", line 352, in <module>
    estimator.train(input_fn=train_input_fn, max_steps=num_train_steps)
  File "C:\Miniconda_python\lib\site-packages\tensorflow_estimator\python\estimator\estimator.py", line 370, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "C:\Miniconda_python\lib\site-packages\tensorflow_estimator\python\estimator\estimator.py", line 1161, in _train_model
    return self._train_model_default(input_fn, hooks, saving_listeners)
  File "C:\Miniconda_python\lib\site-packages\tensorflow_estimator\python\estimator\estimator.py", line 1191, in _train_model_default
    features, labels, ModeKeys.TRAIN, self.config)
  File "C:\Miniconda_python\lib\site-packages\tensorflow_estimator\python\estimator\estimator.py", line 1153, in _call_model_fn
    raise ValueError('model_fn should return an EstimatorSpec.')
ValueError: model_fn should return an EstimatorSpec.

Just wondering what went wrong and needs to be done when loading BERT-Chinese model to fine-tune it for text classification task? Much appreciated

**Comment by jonanem** [comment]
> I tried to run "predicting_movie_reviews_with_bert_on_tf_hub.ipynb", but fine-tuning on a Chinese-text csv with corresponding labels. As such I loaded 'https://tfhub.dev/google/bert_chinese_L-12_H-768_A-12/1' model instead of English-model in the original code
> 
> I only made minimum changes from the original jpynb for data preparation, which was running OK. But during training as in
> estimator.train(input_fn=train_input_fn, max_steps=num_train_steps)
> there was an error of "ValueError: model_fn should return an EstimatorSpec." - Note that I didn't make any modification in model_fn_builder(num_labels, learning_rate, num_train_steps, num_warmup_steps)
> 
> The full error log is as follows - it was running on CPU (8GB RAM) with Windows 10 environment:
> Traceback (most recent call last):
> File "bert_classify.py", line 352, in
> estimator.train(input_fn=train_input_fn, max_steps=num_train_steps)
> File "C:\Miniconda_python\lib\site-packages\tensorflow_estimator\python\estimator\estimator.py", line 370, in train
> loss = self._train_model(input_fn, hooks, saving_listeners)
> File "C:\Miniconda_python\lib\site-packages\tensorflow_estimator\python\estimator\estimator.py", line 1161, in _train_model
> return self._train_model_default(input_fn, hooks, saving_listeners)
> File "C:\Miniconda_python\lib\site-packages\tensorflow_estimator\python\estimator\estimator.py", line 1191, in _train_model_default
> features, labels, ModeKeys.TRAIN, self.config)
> File "C:\Miniconda_python\lib\site-packages\tensorflow_estimator\python\estimator\estimator.py", line 1153, in _call_model_fn
> raise ValueError('model_fn should return an EstimatorSpec.')
> ValueError: model_fn should return an EstimatorSpec.
> 
> Just wondering what went wrong and needs to be done when loading BERT-Chinese model to fine-tune it for text classification task? Much appreciated

Can you please let me know how you are able to fix the issue

**Comment by xinxu75** [comment]
There is no issue on the model, just my mistake
