### ISSUE TITLE
How to splice the other features needed into Bert and fine-tune them together?

### ISSUE THREAD

**Issue by zysNLP** [google-research/bert#931]
In the process of using bert, we don't want to give up our hand-crafted features, such as the length of the sentence, the number of nouns in the sentence, the average length of the words in the sentence, and so on. I know that bert's create_model function in run_classifier has output_layer = model.get_pooled_output() and the output size is [batch_size, hidden_size]. I wander if  it could directly make my above three features to shape [batch_size, 3], Thus concat into [batch_size, hidden_size+3], and then fine-tuned, the problem is that the create_model function can not control the step size of batch_size.

I also think that using the extract_features method mentioned in https://github.com/google-research/bert/issues/201 is not so reasonable. This method seems to use the bert to extract the feature vector separately, then concat to three features together, then Training and validing alone, but if this method lost the role of bert fine-tuning?

Is there anyone realize the concat custom features? Thank you very much!!!

**Comment by isabeauoliveri** [comment]
I probably have the same problem. "Merge" BERT text embedding to my hand-crafted features about novelty and diversity. I would like to implement something that looks like an new intermediate layer that blends the two, using the output as the input for a classic fine tuning operation in BERT. Not something like the #201 . 
I'm trying to understand if this is possible with small changes.

**Comment by zysNLP** [comment]
I tried another way to solve this at #201 maybe help to you. 

> I probably have the same problem. "Merge" BERT text embedding to my hand-crafted features about novelty and diversity. I would like to implement something that looks like an new intermediate layer that blends the two, using the output as the input for a classic fine tuning operation in BERT. Not something like the #201 .
> I'm trying to understand if this is possible with small changes.
