### ISSUE TITLE
Question about calculating word embeddings using pretrained model

### ISSUE THREAD

**Issue by jinj200200** [google-research/bert#940]
In extract_features.py , word embeddings seems to be calculated by summing token, segment and positon embeddings. So the word embedding of "apple" in "Apple is a very good company" and "Apple is a kind of fruit" should be the same. However, I calculate with extract_features.py, the embeddings are NOT the same. What mistake did I make?

**Comment by manueltonneau** [comment]
My understanding is that when using `extract_features.py`, the output are embeddings that the last layer of the BERT pre-trained model outputs. It therefore doesn't have to do with the embeddings that are created as a first step by summing token, segment and position embeddings. This first step is just intended to transform the text into an input for the pre-trained model. I base this on what I read in the documentation, namely that we obtain "pre-trained contextual embeddings, which are fixed contextual representations of each input token generated from the hidden layers of the pre-trained model". Let me know if that makes sense, I may be wrong :)

**Comment by jinj200200** [comment]
> My understanding is that when using extract_features.py, the output are embeddings that the last layer of the BERT pre-trained model outputs. It therefore doesn't have to do with the embeddings that are created as a first step by summing token, segment and position embeddings. This first step is just intended to transform the text into an input for the pre-trained model. I base this on what I read in the documentation, namely that we obtain "pre-trained contextual embeddings, which are fixed contextual representations of each input token generated from the hidden layers of the pre-trained model". Let me know if that makes sense, I may be wrong :)

I think you are right. Thanks a lot.

**Comment by XuJianzhi** [comment]
https://github.com/google-research/bert#using-bert-to-extract-fixed-feature-vectors-like-elmo
