### ISSUE TITLE
How to interprete results

### ISSUE THREAD

**Issue by raff7** [google-research/bert#959]
I am a bit confused.
After the training im left with the following files in the output folder:

train.tf_record
model.ckpt-x.meta
model.ckpt-x.index
model.ckpt-x.data-00000of-x
graph.pbtxt
checkpoints.txt
events.out.tfevents.1575989900.MO-HSK-M-TEC057

i know i have to use the model.ckpt to load the model when testing it, but how do i use the other files to analyse how the training went? is there any helpful information in them? I set the flag "do evaluate" to true, so there should be the results of the evaluations somewhere no? 

thanks.

**Comment by real-brilliant** [comment]
you can track training process by using tensorboard
