### ISSUE TITLE
请问获得训练好的词向量的值？ How to get the pretrained embedding_table?

### ISSUE THREAD

**Issue by WHQ1111** [google-research/bert#971]
I wanted to know how to get the word embedding after I pretrain the model. Are there someone kindly tell me?

**Comment by XuJianzhi** [comment]
https://github.com/google-research/bert#using-bert-to-extract-fixed-feature-vectors-like-elmo

**Comment by limeiyang** [comment]
After get the token_ to_ orig_ Map, how to get the embedding of each word? For example, if a word is divided into three segments, can we directly calculate the average of the three segments?
